project_id = "tribe-neon"

[db]
major_version = 17

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/**"]
enable_signup = true
enable_anonymous_sign_ins = true
enable_manual_linking = true

[realtime]
enabled = true

[storage]
enabled = true

[functions.resolve-battle]
verify_jwt = true
