with checks as (
  select 10 display_order,'main_formation_contract' check_name,
    case when to_regclass('public.user_main_formations') is not null then 'PASS' else 'FAIL' end status,
    'user_main_formations' detail
  union all select 20,'server_power_formula',case when pg_get_functiondef('public.calculate_user_total_power(uuid)'::regprocedure) not like '%base.spd%' and pg_get_functiondef('public.calculate_user_total_power(uuid)'::regprocedure) not like '%base.luk%' then 'PASS' else 'FAIL' end,'HP + ATK + DEF only'
  union all select 30,'empty_formation_zero',case when pg_get_functiondef('public.calculate_user_total_power(uuid)'::regprocedure) like '%coalesce(sum%' then 'PASS' else 'FAIL' end,'empty formation projects zero'
  union all select 40,'client_power_mutation_denied',case when not has_table_privilege('authenticated','public.user_power_rankings','INSERT') and not has_table_privilege('authenticated','public.user_power_rankings','UPDATE') and not has_table_privilege('authenticated','public.user_power_rankings','DELETE') then 'PASS' else 'FAIL' end,'authenticated cannot mutate Power projection'
  union all select 50,'main_formation_mutation_denied',case when not has_table_privilege('authenticated','public.user_main_formations','INSERT') and not has_table_privilege('authenticated','public.user_main_formations','UPDATE') and not has_table_privilege('authenticated','public.user_main_formations','DELETE') then 'PASS' else 'FAIL' end,'RPC-only Main Formation mutation'
  union all select 60,'power_recalculation_triggers',case when count(*)=6 then 'PASS' else 'FAIL' end,count(*)||'/6 trigger(s)' from pg_trigger where not tgisinternal and tgname in('user_character_power_projection_trigger','user_equipment_power_projection_trigger','character_growth_power_projection_trigger','character_awakening_power_projection_trigger','character_battle_power_projection_trigger','equipment_battle_power_projection_trigger')
  union all select 70,'ranking_season_contract',case when count(*)=5 then 'PASS' else 'FAIL' end,count(*)||'/5 active season row(s)' from public.ranking_seasons where status='ACTIVE' and ranking_type in('POWER','GUILD_POWER','PVP','RAID','GVG')
  union all select 80,'daily_jst_contract',case when pg_get_functiondef('public.get_public_power_rankings(boolean,integer,integer)'::regprocedure) like '%Asia/Tokyo%' and pg_get_functiondef('public.capture_pvp_daily_win()'::regprocedure) like '%Asia/Tokyo%' then 'PASS' else 'FAIL' end,'Power and PvP use 00:00 JST calendar day'
  union all select 90,'raid_instance_and_season_contract',case when to_regprocedure('public.get_raid_rankings(uuid)') is not null and pg_get_functiondef('public.get_raid_season_rankings(integer,integer)'::regprocedure) like '%raid_boss_instance_id is not null%' then 'PASS' else 'FAIL' end,'instance daily / explicit season cumulative'
  union all select 100,'gvg_legacy_client_denied',case when not has_table_privilege('authenticated','public.user_gvg_ranks','SELECT') and not has_table_privilege('authenticated','public.guild_base_controls','UPDATE') then 'PASS' else 'FAIL' end,'old point path unavailable to consumer'
  union all select 110,'raw_competition_mutation_denied',case when not has_table_privilege('authenticated','public.raid_damage_logs','INSERT') and not has_table_privilege('authenticated','public.raid_damage_logs','UPDATE') and not has_table_privilege('authenticated','public.raid_damage_logs','DELETE') then 'PASS' else 'FAIL' end,'Raid raw log mutation denied'
  union all select 120,'public_rpc_hardening',case when count(distinct p.proname)=10 then 'PASS' else 'FAIL' end,count(distinct p.proname)||'/10 hardened public RPC name(s)' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('save_main_formation','get_current_main_formation','get_my_power_snapshot','get_public_power_rankings','get_public_guild_power_rankings','get_public_pvp_rankings','get_raid_season_rankings','get_public_gvg_rankings','get_active_ranking_seasons','get_public_player_detail') and p.prosecdef and coalesce(p.proconfig,array[]::text[])@>array['search_path=public']
  union all select 130,'anon_denied',case when count(*)=0 then 'PASS' else 'FAIL' end,count(*)||' unexpectedly executable function(s)' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('save_main_formation','get_current_main_formation','get_my_power_snapshot','get_public_power_rankings','get_public_guild_power_rankings','get_public_pvp_rankings','get_raid_season_rankings','get_public_gvg_rankings','get_active_ranking_seasons','get_public_player_detail') and has_function_privilege('anon',p.oid,'EXECUTE')
)
select * from checks order by display_order;
