with checks(display_order,check_name,status,detail) as(
 select 10,'funnel_tables',case when count(*)=2 then 'PASS' else 'FAIL' end,count(*)||'/2 table(s)' from information_schema.tables where table_schema='public' and table_name in('user_funnel_milestones','client_funnel_events')
 union all select 20,'required_functions',case when count(*)=6 then 'PASS' else 'FAIL' end,count(*)||'/6 function(s)' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('record_funnel_milestone','record_client_funnel_event','on_official_battle_funnel','on_guild_funnel','on_guild_chat_activation','get_recommended_guilds')
 union all select 30,'server_milestone_triggers',case when count(*)=4 then 'PASS' else 'FAIL' end,count(*)||'/4 trigger(s)' from pg_trigger where not tgisinternal and tgname in('official_battle_funnel_trigger','guild_join_request_funnel_trigger','guild_member_funnel_trigger','guild_chat_activation_funnel_trigger')
 union all select 40,'internal_milestone_write_denied',case when not has_function_privilege('authenticated','public.record_funnel_milestone(uuid,text,jsonb)','EXECUTE') and not has_function_privilege('anon','public.record_funnel_milestone(uuid,text,jsonb)','EXECUTE') then 'PASS' else 'FAIL' end,'consumer cannot forge server milestones'
 union all select 50,'allowlisted_client_event',case when has_function_privilege('authenticated','public.record_client_funnel_event(text,text,text,text,jsonb)','EXECUTE') and not has_function_privilege('anon','public.record_client_funnel_event(text,text,text,text,jsonb)','EXECUTE') then 'PASS' else 'FAIL' end,'authenticated allowlist event contract'
 union all select 60,'recommendation_contract',case when has_function_privilege('authenticated','public.get_recommended_guilds(integer)','EXECUTE') and not has_function_privilege('anon','public.get_recommended_guilds(integer)','EXECUTE') then 'PASS' else 'FAIL' end,'authenticated 3-5 active/open Guild candidates'
)
select * from checks order by display_order;
