with checks(display_order,check_name,status,detail) as (
 select 10,'funnel_mission_master',case when count(*)=9 and bool_and(is_enabled and is_provisional) then 'PASS' else 'FAIL' end,count(*)||'/9 enabled provisional row(s)' from public.missions where id like 'ob_funnel_%'
 union all select 20,'recommendation_weight_master',case when count(*)=11 and bool_and(is_provisional) then 'PASS' else 'FAIL' end,count(*)||'/11 replaceable weight(s)' from public.guild_recommendation_weights
 union all select 30,'recommendation_v11_contract',case when pg_get_functiondef('public.get_recommended_guilds(integer)'::regprocedure) like '%raid_participants_7d%' and pg_get_functiondef('public.get_recommended_guilds(integer)'::regprocedure) like '%stale_requests%' then 'PASS' else 'FAIL' end,'activity, density, Raid, power, approval, stale request and rotation signals'
 union all select 40,'mission_progress_trigger',case when count(*)=1 then 'PASS' else 'FAIL' end,count(*)||'/1 trigger(s)' from pg_trigger where not tgisinternal and tgname='funnel_mission_progress_trigger'
 union all select 50,'analytics_allowlist',case when pg_get_functiondef('public.record_client_funnel_event(text,text,text,text,jsonb)'::regprocedure) like '%home_primary_cta_click%' and pg_get_functiondef('public.record_client_funnel_event(text,text,text,text,jsonb)'::regprocedure) like '%guild_chat_raid_click%' then 'PASS' else 'FAIL' end,'P0+ navigation events are allowlisted'
 union all select 60,'internal_execute_denied',case when not has_function_privilege('authenticated','public.on_funnel_mission_progress()','EXECUTE') and not has_function_privilege('authenticated','public.funnel_mission_trigger_type(text)','EXECUTE') then 'PASS' else 'FAIL' end,'internal mission hooks are not consumer-callable'
 union all select 70,'client_master_write_denied',case when not has_table_privilege('authenticated','public.guild_recommendation_weights','INSERT') and not has_table_privilege('authenticated','public.guild_recommendation_weights','UPDATE') and not has_table_privilege('authenticated','public.guild_recommendation_weights','DELETE') then 'PASS' else 'FAIL' end,'authenticated cannot alter Recommendation weights'
)
select * from checks order by display_order;
