// Master data for Skill Cards (Total: 70 Skills + 2 System Basic Skills)
// Clean zero-based rebuild for Timeline 5v5 Auto Battle

export interface SkillCardMaster {
  id: string;
  name: string;
  rarity: string;
  alignment: string; // 属性 (JUSTICE, EVIL, ORDER, CHAOS)
  ap_cost: number;
  power: number;
  effect_type: string; // ATTACK, DEFENSE, HEAL, SUPPORT, JAMMER
  is_exclusive: boolean;
  exclusive_character_id: string | null;
  description: string;
  is_obtainable?: boolean; // ガチャ・所持一覧排除用ガードフラグ (デフォルトtrue、通常行動のみfalse)
}

// System Basic Skills (Not obtainable via Gacha or User Inventory)
export const SKILL_BASIC_ATTACK: SkillCardMaster = {
  id: "SKILL_BASIC_ATTACK",
  name: "通常攻撃",
  rarity: "N",
  alignment: "ORDER",
  ap_cost: 0,
  power: 30,
  effect_type: "ATTACK",
  is_exclusive: false,
  exclusive_character_id: null,
  description: "基本となる素手または近接武器での通常攻撃。",
  is_obtainable: false
};

export const SKILL_BASIC_DEFENSE: SkillCardMaster = {
  id: "SKILL_BASIC_DEFENSE",
  name: "通常防御",
  rarity: "N",
  alignment: "ORDER",
  ap_cost: 0,
  power: 25,
  effect_type: "DEFENSE",
  is_exclusive: false,
  exclusive_character_id: null,
  description: "基本となる身構えとガード体制。",
  is_obtainable: false
};

export const SKILLS_MASTER_DATA: SkillCardMaster[] = [
  // ==========================================
  // ① N (Normal) レアリティ (10種: SKILL_001〜SKILL_010) AP: 1
  // ==========================================
  {
    id: "SKILL_001",
    name: "ストリートパンチ",
    rarity: "N",
    alignment: "JUSTICE",
    ap_cost: 1,
    power: 50,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "喧嘩慣れした路地裏仕込みの鋭いストレート。",
    is_obtainable: true
  },
  {
    id: "SKILL_002",
    name: "クイックシールド",
    rarity: "N",
    alignment: "ORDER",
    ap_cost: 1,
    power: 40,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "暴徒の突撃に備え、軽量防犯盾を即座に構える。",
    is_obtainable: true
  },
  {
    id: "SKILL_003",
    name: "ノイズヒール",
    rarity: "N",
    alignment: "CHAOS",
    ap_cost: 1,
    power: 30,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "違法ルートで入手した即効性の痛み止めサプリメントを服用して傷を癒やす。",
    is_obtainable: true
  },
  {
    id: "SKILL_004",
    name: "ステップダッシュ",
    rarity: "N",
    alignment: "CHAOS",
    ap_cost: 1,
    power: 15,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "俊敏なフットワークで間合いを詰め、身のこなしを鋭くする。",
    is_obtainable: true
  },
  {
    id: "SKILL_005",
    name: "毒針",
    rarity: "N",
    alignment: "EVIL",
    ap_cost: 1,
    power: 10,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "毒素を塗布した極細の暗器を敵の防具の隙間に突き刺す。",
    is_obtainable: true
  },
  {
    id: "SKILL_006",
    name: "アイアンガード",
    rarity: "N",
    alignment: "ORDER",
    ap_cost: 1,
    power: 15,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "身につけた防弾プロテクターのガードを一時的に固める。",
    is_obtainable: true
  },
  {
    id: "SKILL_007",
    name: "罵詈雑言",
    rarity: "N",
    alignment: "CHAOS",
    ap_cost: 1,
    power: 20,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "荒々しいストリートのスラングで敵を挑発し、注意を自分に向ける。",
    is_obtainable: true
  },
  {
    id: "SKILL_008",
    name: "スマートスナイプ",
    rarity: "N",
    alignment: "ORDER",
    ap_cost: 1,
    power: 40,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "改良型レーザー照準器により、ターゲットを確実に射止める。",
    is_obtainable: true
  },
  {
    id: "SKILL_009",
    name: "ドーピング注射",
    rarity: "N",
    alignment: "EVIL",
    ap_cost: 1,
    power: 20,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "合成ドラッグを注入し、一時的に痛覚を麻痺させて攻撃力を上げる。",
    is_obtainable: true
  },
  {
    id: "SKILL_010",
    name: "ライトフラッシュ",
    rarity: "N",
    alignment: "JUSTICE",
    ap_cost: 1,
    power: 20,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "超高輝度のフラッシュライトを敵の顔面に照射し、一時的に視界を奪う。",
    is_obtainable: true
  },

  // ==========================================
  // ② R (Rare) レアリティ (10種: SKILL_011〜SKILL_020) AP: 2
  // ==========================================
  {
    id: "SKILL_011",
    name: "チャージスラッシュ",
    rarity: "R",
    alignment: "ORDER",
    ap_cost: 2,
    power: 100,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "体重を完全に乗せ、凄まじい速度で振り下ろす仕込み日本刀の斬撃。",
    is_obtainable: true
  },
  {
    id: "SKILL_012",
    name: "大旋風パイプ",
    rarity: "R",
    alignment: "CHAOS",
    ap_cost: 2,
    power: 45,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "鉄パイプや金属バットを力任せに横一線に振り回し、群がる敵をなぎ払う。",
    is_obtainable: true
  },
  {
    id: "SKILL_013",
    name: "フィールド応急手当",
    rarity: "R",
    alignment: "ORDER",
    ap_cost: 2,
    power: 70,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "安全な遮蔽物の陰で呼吸を整え、軍用止血スプレーで傷口を塞ぐ。",
    is_obtainable: true
  },
  {
    id: "SKILL_014",
    name: "スモークスクリーン",
    rarity: "R",
    alignment: "CHAOS",
    ap_cost: 2,
    power: 15,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "化学煙幕を放つ発煙筒を足元に叩きつけ、味方の輪郭を隠蔽する。",
    is_obtainable: true
  },
  {
    id: "SKILL_015",
    name: "強酸アジドスプレー",
    rarity: "R",
    alignment: "EVIL",
    ap_cost: 2,
    power: 25,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "相手のタクティカルベストや防具を急速に脆化させる強酸スプレーを噴射する。",
    is_obtainable: true
  },
  {
    id: "SKILL_016",
    name: "ライオットバリア",
    rarity: "R",
    alignment: "ORDER",
    ap_cost: 2,
    power: 75,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "防犯・防刃仕様の大型ライオットシールドを構え、強固な防壁となる。",
    is_obtainable: true
  },
  {
    id: "SKILL_017",
    name: "不屈の怒号",
    rarity: "R",
    alignment: "JUSTICE",
    ap_cost: 2,
    power: 15,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "腹の底からの咆哮で味方の士気を極限まで高める。",
    is_obtainable: true
  },
  {
    id: "SKILL_018",
    name: "高圧電撃警棒",
    rarity: "R",
    alignment: "EVIL",
    ap_cost: 2,
    power: 30,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "特製のスタン警棒で首筋を強打し、高圧電流で1ターン行動不能に陥れる。",
    is_obtainable: true
  },
  {
    id: "SKILL_019",
    name: "バーストラッシュ",
    rarity: "R",
    alignment: "CHAOS",
    ap_cost: 2,
    power: 85,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "素早い踏み込みから怒涛の打撃を叩き込み、ダメージの30%分自身のHPを回復する。",
    is_obtainable: true
  },
  {
    id: "SKILL_020",
    name: "タクティカルリロード",
    rarity: "R",
    alignment: "ORDER",
    ap_cost: 2,
    power: 20,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "銃器のマガジンを電光石火で交換し、部隊の行動APを即座に還元する。",
    is_obtainable: true
  },

  // ==========================================
  // ③ SR (Super Rare) レアリティ (15種: SKILL_021〜SKILL_035) AP: 3
  // ==========================================
  {
    id: "SKILL_021",
    name: "急所撃ち",
    rarity: "SR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 160,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "防具の隙間を的確に狙い、壊滅的な痛打を与える。",
    is_obtainable: true
  },
  {
    id: "SKILL_022",
    name: "重鉄パイプ大薙ぎ",
    rarity: "SR",
    alignment: "CHAOS",
    ap_cost: 3,
    power: 80,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "極太の鉄パイプを豪快に一振りし、敵全体にダメージと防具破損を与える。",
    is_obtainable: true
  },
  {
    id: "SKILL_023",
    name: "軍用止血パック",
    rarity: "SR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 120,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "闇ルートで確保した軍用医療キットを展開し、味方全員の傷を急速手当する。",
    is_obtainable: true
  },
  {
    id: "SKILL_024",
    name: "機動防犯盾陣形",
    rarity: "SR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 110,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "大型防犯盾を並べ、敵の一斉攻撃を防ぐ強固な陣形を張る。",
    is_obtainable: true
  },
  {
    id: "SKILL_025",
    name: "催涙ガス噴射",
    rarity: "SR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 20,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "広範囲に高濃度催涙ガスを散布し、敵全員の攻撃力を削ぐ。",
    is_obtainable: true
  },
  {
    id: "SKILL_026",
    name: "決起のシュプレヒコール",
    rarity: "SR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 20,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "組織の誇りをかけた勝吼で、チーム全員の全能力を引き上げる。",
    is_obtainable: true
  },
  {
    id: "SKILL_027",
    name: "血の強襲",
    rarity: "SR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 130,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "鋭利な仕込み刃で切り裂く。対象が出血中なら威力+50%の致命傷を与える。",
    is_obtainable: true
  },
  {
    id: "SKILL_028",
    name: "シールドクラッシャー",
    rarity: "SR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 100,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "鍛え上げたハンマーで叩きつけ、敵の防犯シールドに対して3倍の激突ダメージを与える。",
    is_obtainable: true
  },
  {
    id: "SKILL_029",
    name: "継続処置薬",
    rarity: "SR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 40,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "継続的な持続処置サプリを処方し、味方全体の手番ごとにHPを回復させる。",
    is_obtainable: true
  },
  {
    id: "SKILL_030",
    name: "暗号ジャミング",
    rarity: "SR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 30,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "強力な通信妨害ノイズを流し、1ターン敵の装備スキル発動を封じる。",
    is_obtainable: true
  },
  {
    id: "SKILL_031",
    name: "カウンタースパイク",
    rarity: "SR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 60,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "トゲ付き防具を構え、自身にシールド付与および受けた攻撃の40%を撃ち返す。",
    is_obtainable: true
  },
  {
    id: "SKILL_032",
    name: "暗器・毒塗りの刃",
    rarity: "SR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 90,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "猛毒を塗った暗器で急所を突き、強い毒毒素を注入する。",
    is_obtainable: true
  },
  {
    id: "SKILL_033",
    name: "精神統一・明鏡止水",
    rarity: "SR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 30,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "深呼吸で極限の集中状態に入り、全ての弱体効果を払拭して動体視力を跳ね上げる。",
    is_obtainable: true
  },
  {
    id: "SKILL_034",
    name: "フラッシュバン強襲",
    rarity: "SR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 50,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "超高輝度閃光弾を投げつけ、敵全体の視界を長時間狂わせる。",
    is_obtainable: true
  },
  {
    id: "SKILL_035",
    name: "アドレナリンフル開花",
    rarity: "SR",
    alignment: "CHAOS",
    ap_cost: 3,
    power: 40,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "高濃度アドレナリンを直接心臓へ投与し、生命力を削って極限の破壊力を得る。",
    is_obtainable: true
  },

  // ==========================================
  // ④ SSR (Double Super Rare) レアリティ (15種: SKILL_036〜SKILL_050) AP: 4
  // ==========================================
  {
    id: "SKILL_036",
    name: "一騎当千・無慈悲の一撃",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 280,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "渾身の力と殺意を込めた一撃を叩き込み、敵1体を確定破壊する。",
    is_obtainable: true
  },
  {
    id: "SKILL_037",
    name: "広域アサルトフルバースト",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 140,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "アサルトライフルを全弾掃射し、敵チーム全体に壊滅的な弾幕を浴びせる。",
    is_obtainable: true
  },
  {
    id: "SKILL_038",
    name: "絶対防御・鉄壁の要塞",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 220,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "軍用最高峰の防弾プレート陣形を展開し、あらゆる大技を遮断する。",
    is_obtainable: true
  },
  {
    id: "SKILL_039",
    name: "奇跡の野戦救急執刀",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 200,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "闇医者の神業により、全員の致命傷を治癒し全デバフを即座に洗い流す。",
    is_obtainable: true
  },
  {
    id: "SKILL_040",
    name: "漆黒の広域強酸大散布",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 30,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "大容量タンクから強酸と毒ガスを一斉散布し、敵チーム全体を3ターン壊滅状態に追い込む。",
    is_obtainable: true
  },
  {
    id: "SKILL_041",
    name: "王者の決起・天下布武",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 25,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "組織の頂点に立つ者の咆哮が味方全員の潜在能力を極限まで呼び覚ます。",
    is_obtainable: true
  },
  {
    id: "SKILL_042",
    name: "血宴の絶影・連撃",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 200,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "闇から一瞬で踏み込み急所を連撃。ダメージの50%分回復し強い出血を付与する。",
    is_obtainable: true
  },
  {
    id: "SKILL_043",
    name: "壊滅のグランドスラム",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 160,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "大ハンマーで地面を叩き割る衝撃波。全体ダメージとともに30%の確率で気絶させる。",
    is_obtainable: true
  },
  {
    id: "SKILL_044",
    name: "狂犬の血の復讐",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 220,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "己の血を流すほど威力が爆発。HPが減少しているほど威力が跳ね上がる捨て身技。",
    is_obtainable: true
  },
  {
    id: "SKILL_045",
    name: "戦術指揮・総攻撃",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 30,
    effect_type: "SUPPORT",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "的な戦術指示により全員の火力を跳ね上げ、部隊APを大量回復する。",
    is_obtainable: true
  },
  {
    id: "SKILL_046",
    name: "毒蜘蛛の檻",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 70,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "敵陣全体に遅効性の致死毒アンプルを破裂させ、毎ターン強烈な毒ダメージを与える。",
    is_obtainable: true
  },
  {
    id: "SKILL_047",
    name: "反撃の装甲要塞",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 150,
    effect_type: "DEFENSE",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "全員に分厚い装甲シールドを付与し、受ける攻撃の25%を全攻撃者に撃ち返す。",
    is_obtainable: true
  },
  {
    id: "SKILL_048",
    name: "不屈の生命力",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 80,
    effect_type: "HEAL",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "精神力を極限まで高め、毎ターン大幅なHP回復を3ターン持続させる。",
    is_obtainable: true
  },
  {
    id: "SKILL_049",
    name: "無力化の広域閃光爆弾",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 40,
    effect_type: "JAMMER",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "特殊閃光音響弾を爆発させ、敵全体の視界と通信を完全に封鎖する。",
    is_obtainable: true
  },
  {
    id: "SKILL_050",
    name: "決戦の一閃・断罪",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 250,
    effect_type: "ATTACK",
    is_exclusive: false,
    exclusive_character_id: null,
    description: "あらゆる防具・シールドを一切無視し、HPへダイレクトに大撃打を突き刺す。",
    is_obtainable: true
  },

  // ==========================================
  // ⑤ キャラ専用枠 (20種: SKILL_051〜SKILL_070 / 採番枠確保) AP: 3〜4
  // ==========================================
  {
    id: "SKILL_051",
    name: "専用スキル枠_01",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 180,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠01・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_052",
    name: "専用スキル枠_02",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 180,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠02・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_053",
    name: "専用スキル枠_03",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 140,
    effect_type: "DEFENSE",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠03・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_054",
    name: "専用スキル枠_04",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 3,
    power: 140,
    effect_type: "HEAL",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠04・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_055",
    name: "専用スキル枠_05",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 3,
    power: 20,
    effect_type: "SUPPORT",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠05・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_056",
    name: "専用スキル枠_06",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 3,
    power: 20,
    effect_type: "JAMMER",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠06・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_057",
    name: "専用スキル枠_07",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 3,
    power: 200,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠07・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_058",
    name: "専用スキル枠_08",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 3,
    power: 160,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠08・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_059",
    name: "専用スキル枠_09",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 240,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠09・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_060",
    name: "専用スキル枠_10",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 240,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠10・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_061",
    name: "専用スキル枠_11",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 200,
    effect_type: "DEFENSE",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠11・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_062",
    name: "専用スキル枠_12",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 180,
    effect_type: "HEAL",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠12・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_063",
    name: "専用スキル枠_13",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 30,
    effect_type: "SUPPORT",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠13・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_064",
    name: "専用スキル枠_14",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 30,
    effect_type: "JAMMER",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠14・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_065",
    name: "専用スキル枠_15",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 260,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠15・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_066",
    name: "専用スキル枠_16",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 220,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠16・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_067",
    name: "専用スキル枠_17",
    rarity: "SSR",
    alignment: "JUSTICE",
    ap_cost: 4,
    power: 250,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠17・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_068",
    name: "専用スキル枠_18",
    rarity: "SSR",
    alignment: "EVIL",
    ap_cost: 4,
    power: 250,
    effect_type: "ATTACK",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠18・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_069",
    name: "専用スキル枠_19",
    rarity: "SSR",
    alignment: "ORDER",
    ap_cost: 4,
    power: 30,
    effect_type: "SUPPORT",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠19・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  },
  {
    id: "SKILL_070",
    name: "専用スキル枠_20",
    rarity: "SSR",
    alignment: "CHAOS",
    ap_cost: 4,
    power: 30,
    effect_type: "JAMMER",
    is_exclusive: true,
    exclusive_character_id: null,
    description: "【専用枠20・後日確定】キャラ60種化フェーズにて各キャラの個性と連動して正式設定される専用スキル。",
    is_obtainable: true
  }
];
