import fs from "node:fs";

const questMaster = JSON.parse(fs.readFileSync("src/domain/gameplay/canonical/data/quests_20260822.json", "utf8"));
const encounterMaster = JSON.parse(fs.readFileSync("src/domain/gameplay/canonical/data/quest_encounters_20260822.json", "utf8"));
if (questMaster.quests.length !== 21 || encounterMaster.encounters.length !== 21 || questMaster.unresolvedContracts.length !== 0) {
  throw new Error("Canonical Quest master is not ready for migration generation");
}
const poolRows = questMaster.rewardPools.flatMap((pool) => pool.items.map((item, index) => ({
  rewardPoolId: pool.rewardPoolId,
  rollIndex: index + 1,
  ...item,
})));
const q = JSON.stringify(questMaster.quests);
const p = JSON.stringify(poolRows);
const e = JSON.stringify(encounterMaster.encounters);
const sql = `-- Generated by scripts/generate_quest_production_db_migration.mjs. Do not hand-edit seed values.
begin;

create table if not exists public.canonical_quest_master (
 version text not null, quest_id text not null, town_id text not null, difficulty text not null,
 display_name text not null, display_order integer not null, duration_sec integer not null,
 vitality_cost integer not null, user_exp integer not null, cash_reward integer not null,
 first_clear_user_exp integer not null, reward_pool_id text not null, first_clear_reward_pool_id text not null,
 enemy_encounter_id text not null, unlock_condition text not null check(unlock_condition='NONE'),
 is_production_enabled boolean not null, primary key(version,quest_id)
);
create table if not exists public.canonical_quest_reward_pool_items (
 version text not null, reward_pool_id text not null, roll_index integer not null,
 item_id text not null, quantity integer not null check(quantity>0), probability_bp integer not null check(probability_bp between 0 and 10000),
 primary key(version,reward_pool_id,roll_index)
);
create table if not exists public.canonical_quest_encounter_master (
 version text not null, encounter_id text not null, quest_id text not null, town_id text not null,
 difficulty text not null, members jsonb not null, normal_attack_power_bp integer not null check(normal_attack_power_bp=8000),
 tuning_status text not null, is_production_enabled boolean not null, primary key(version,encounter_id), unique(version,quest_id)
);

insert into public.canonical_quest_master(version,quest_id,town_id,difficulty,display_name,display_order,duration_sec,vitality_cost,user_exp,cash_reward,first_clear_user_exp,reward_pool_id,first_clear_reward_pool_id,enemy_encounter_id,unlock_condition,is_production_enabled)
select '2026-08-22',"questId","townId",difficulty,name,"displayOrder","durationSec","vitalityCost","userExp","cashReward","firstClearUserExp","rewardPoolId",
 case difficulty when 'EASY' then 'QUEST_FIRST_EASY' when 'NORMAL' then 'QUEST_FIRST_NORMAL' else 'QUEST_FIRST_HARD' end,
 "enemyEncounterId","unlockCondition","isProductionEnabled"
from jsonb_to_recordset($quests$${q}$quests$::jsonb) as r("questId" text,"townId" text,difficulty text,name text,"displayOrder" integer,"durationSec" integer,"vitalityCost" integer,"userExp" integer,"cashReward" integer,"firstClearUserExp" integer,"rewardPoolId" text,"enemyEncounterId" text,"unlockCondition" text,"isProductionEnabled" boolean)
on conflict(version,quest_id) do update set town_id=excluded.town_id,difficulty=excluded.difficulty,display_name=excluded.display_name,display_order=excluded.display_order,duration_sec=excluded.duration_sec,vitality_cost=excluded.vitality_cost,user_exp=excluded.user_exp,cash_reward=excluded.cash_reward,first_clear_user_exp=excluded.first_clear_user_exp,reward_pool_id=excluded.reward_pool_id,first_clear_reward_pool_id=excluded.first_clear_reward_pool_id,enemy_encounter_id=excluded.enemy_encounter_id,unlock_condition=excluded.unlock_condition,is_production_enabled=excluded.is_production_enabled;

insert into public.canonical_quest_reward_pool_items(version,reward_pool_id,roll_index,item_id,quantity,probability_bp)
select '2026-08-22',"rewardPoolId","rollIndex","itemId",quantity,"probabilityBp"
from jsonb_to_recordset($pools$${p}$pools$::jsonb) as r("rewardPoolId" text,"rollIndex" integer,"itemId" text,quantity integer,"probabilityBp" integer)
on conflict(version,reward_pool_id,roll_index) do update set item_id=excluded.item_id,quantity=excluded.quantity,probability_bp=excluded.probability_bp;

insert into public.canonical_quest_encounter_master(version,encounter_id,quest_id,town_id,difficulty,members,normal_attack_power_bp,tuning_status,is_production_enabled)
select '2026-08-22',"encounterId","questId","townId",difficulty,members,"normalAttackPowerBp","tuningStatus","isProductionEnabled"
from jsonb_to_recordset($encounters$${e}$encounters$::jsonb) as r("encounterId" text,"questId" text,"townId" text,difficulty text,members jsonb,"normalAttackPowerBp" integer,"tuningStatus" text,"isProductionEnabled" boolean)
on conflict(version,encounter_id) do update set quest_id=excluded.quest_id,town_id=excluded.town_id,difficulty=excluded.difficulty,members=excluded.members,normal_attack_power_bp=excluded.normal_attack_power_bp,tuning_status=excluded.tuning_status,is_production_enabled=excluded.is_production_enabled;

update public.quests legacy set duration_seconds=master.duration_sec,cost_vitality=master.vitality_cost,cash_reward=master.cash_reward,exp_reward=master.user_exp,
 item_rewards=(select coalesce(jsonb_agg(jsonb_build_object('item_id',item.item_id,'quantity',item.quantity,'chance',item.probability_bp::numeric/10000) order by item.roll_index),'[]'::jsonb) from public.canonical_quest_reward_pool_items item where item.version=master.version and item.reward_pool_id=master.reward_pool_id)
from public.canonical_quest_master master where master.version='2026-08-22' and master.quest_id=legacy.id;

create table if not exists public.user_quest_first_clears (
 user_id uuid not null references auth.users(id) on delete cascade,
 quest_id text not null references public.quests(id), cleared_at timestamptz not null default now(),
 primary key(user_id,quest_id)
);
insert into public.user_quest_first_clears(user_id,quest_id,cleared_at)
select distinct patrol.user_id,coalesce(patrol.course_id,patrol.quest_id),coalesce(patrol.started_at,now())
from public.user_patrols patrol where patrol.status='COMPLETED' and coalesce(patrol.course_id,patrol.quest_id) is not null
on conflict(user_id,quest_id) do nothing;

alter table public.users add column if not exists quest_free_skips_count integer not null default 0,
 add column if not exists quest_paid_skips_count integer not null default 0,
 add column if not exists quest_skips_reset_date date;

create or replace function public.start_patrol(p_course_id text,p_character_id text) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_character_id text; v_q record; v_vitality integer; v_active integer; v_id uuid;
begin
 if v_user_id is null then raise exception 'authentication required' using errcode='42501'; end if;
 select * into v_q from public.canonical_quest_master where version='2026-08-22' and quest_id=p_course_id and is_production_enabled and unlock_condition='NONE';
 if not found then raise exception 'quest master not found' using errcode='23503'; end if;
 if not exists(select 1 from public.canonical_quest_encounter_master where version='2026-08-22' and encounter_id=v_q.enemy_encounter_id and is_production_enabled) then raise exception 'quest encounter not found' using errcode='23503'; end if;
 select owned.character_id into v_character_id from public.user_characters owned where owned.user_id=v_user_id and (owned.id::text=p_character_id or owned.character_id=p_character_id) order by (owned.id::text=p_character_id) desc limit 1;
 if v_character_id is null then raise exception 'character is not owned' using errcode='23503'; end if;
 select count(*) into v_active from public.user_patrols where user_id=v_user_id and status<>'COMPLETED';
 if v_active>=5 then raise exception 'all dispatch slots are occupied' using errcode='23514'; end if;
 if exists(select 1 from public.user_patrols where user_id=v_user_id and character_id=v_character_id and status<>'COMPLETED') then raise exception 'character is already dispatched' using errcode='23505'; end if;
 perform public.sync_and_recover_vitality_and_pvp_points(v_user_id);
 select vitality into v_vitality from public.users where id=v_user_id for update;
 if coalesce(v_vitality,0)<v_q.vitality_cost then raise exception 'insufficient vitality' using errcode='23514'; end if;
 insert into public.user_patrols(user_id,course_id,character_id,started_at,expires_at,status,has_battle_event,battle_resolved)
 values(v_user_id,p_course_id,v_character_id,now(),now()+v_q.duration_sec*interval '1 second','ONGOING',true,false) returning id into v_id;
 update public.users set vitality=vitality-v_q.vitality_cost,vitality_last_recovered_at=case when vitality>=100 then now() else vitality_last_recovered_at end where id=v_user_id;
 return jsonb_build_object('status','success','patrol_id',v_id,'has_battle',true,'duration_seconds',v_q.duration_sec,'cost_vitality',v_q.vitality_cost,'remaining_vitality',v_vitality-v_q.vitality_cost);
end $$;

create or replace function public.complete_patrol_instantly(p_user_id uuid,p_patrol_id uuid,p_use_currency text) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_currency text:=upper(coalesce(p_use_currency,'')); v_status text; v_free integer; v_paid integer; v_reset date; v_today date:=(now() at time zone 'Asia/Tokyo')::date; v_step text;
begin
 if v_uid is null or v_uid<>p_user_id then raise exception 'not authorized' using errcode='42501'; end if;
 select status into v_status from public.user_patrols where id=p_patrol_id and user_id=v_uid for update;
 if v_status is null then raise exception 'patrol not found' using errcode='P0002'; end if;
 if v_status<>'ONGOING' then raise exception 'patrol is not eligible for instant completion' using errcode='23514'; end if;
 if v_currency='FREE_TUTORIAL' then
  select step_id into v_step from public.tutorial_progress where user_id=v_uid for update;
  if v_step<>'FREE_INSTANT' then raise exception 'tutorial free instant completion is unavailable' using errcode='55000'; end if;
  update public.tutorial_progress set step_id='TUTORIAL_BATTLE',updated_at=now() where user_id=v_uid and step_id='FREE_INSTANT';
 elsif v_currency in ('FREE_PREOPEN','FREE') then
  select quest_free_skips_count,quest_paid_skips_count,quest_skips_reset_date into v_free,v_paid,v_reset from public.users where id=v_uid for update;
  if v_reset is distinct from v_today then v_free:=0; v_paid:=0; end if;
  if v_free>=5 then raise exception 'daily free instant completion limit reached' using errcode='23514'; end if;
  update public.users set quest_free_skips_count=v_free+1,quest_paid_skips_count=v_paid,quest_skips_reset_date=v_today where id=v_uid;
 elsif v_currency='DIAMOND' then
  select quest_free_skips_count,quest_paid_skips_count,quest_skips_reset_date into v_free,v_paid,v_reset from public.users where id=v_uid for update;
  if v_reset is distinct from v_today then v_free:=0; v_paid:=0; end if;
  if v_paid>=10 then raise exception 'daily paid instant completion limit reached' using errcode='23514'; end if;
  if (select neon_diamonds from public.users where id=v_uid)<30 then raise exception 'diamond insufficient' using errcode='23514'; end if;
  update public.users set neon_diamonds=neon_diamonds-30,quest_free_skips_count=v_free,quest_paid_skips_count=v_paid+1,quest_skips_reset_date=v_today where id=v_uid;
 else raise exception 'invalid patrol instant completion currency' using errcode='22023'; end if;
 update public.user_patrols set status='CLAIMABLE',expires_at=now() where id=p_patrol_id and user_id=v_uid;
 return jsonb_build_object('status','success','patrol_id',p_patrol_id,'currency',v_currency,'diamond_cost',case when v_currency='DIAMOND' then 30 else 0 end,'free_skips_remaining',case when v_currency in ('FREE_PREOPEN','FREE') then 4-v_free else null end,'paid_skips_remaining',case when v_currency='DIAMOND' then 9-v_paid else null end,'tutorial_step',case when v_currency='FREE_TUTORIAL' then 'TUTORIAL_BATTLE' else null end);
end $$;

create or replace function public.canonical_quest_enemy_snapshot(p_quest_id text) returns jsonb
language sql stable security definer set search_path=public as $$
 with encounter as (select * from public.canonical_quest_encounter_master where version='2026-08-22' and quest_id=p_quest_id and is_production_enabled),
 members as (select value member,ordinality from encounter,jsonb_array_elements(encounter.members) with ordinality),
 resolved as (select encounter.encounter_id,members.ordinality,members.member,master.display_name,master.attribute,stats.* from encounter join members on true join public.canonical_character_master master on master.version='2026-08-21' and master.character_id=members.member->>'characterId' cross join lateral public.canonical_character_stats(members.member->>'characterId',(members.member->>'level')::integer,0) stats)
 select jsonb_agg(jsonb_build_object('id','enemy_'||encounter_id||'_'||ordinality,'characterId',member->>'characterId','name',display_name,'team','ENEMY','alignment',attribute,'level',(member->>'level')::integer,'awakeningLevel',0,'stats',jsonb_build_object('hp',hp,'atk',atk,'def',def,'spd',spd,'luk',luk),'equipment','[]'::jsonb,'equippedSkillRefs','[]'::jsonb,'skills',jsonb_build_array(jsonb_build_object('id','BASIC_ATTACK','name','通常攻撃','activationType','ACTIVE','cooldown',0,'availableFromRound',1,'target','ENEMY_SINGLE','effects',jsonb_build_array('DAMAGE 80% ATK')))) order by ordinality) from resolved
$$;

create or replace function public.create_patrol_battle_replay(p_patrol_id uuid,p_tactic_id text default 'ATTACK_PRIORITY') returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_patrol record; v_ids text[]; v_player jsonb; v_enemy jsonb; v_replay uuid; v_seed bigint;
begin
 if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if;
 if p_tactic_id not in ('ATTACK_PRIORITY','HEAL_PRIORITY','SKILL_PRIORITY','BALANCED','WEAKNESS_FOCUS') then raise exception 'invalid tactic' using errcode='22023'; end if;
 select patrol.* into v_patrol from public.user_patrols patrol join public.canonical_quest_master quest on quest.version='2026-08-22' and quest.quest_id=coalesce(patrol.course_id,patrol.quest_id) and quest.is_production_enabled where patrol.id=p_patrol_id and patrol.user_id=v_uid and (patrol.status='CLAIMABLE' or (patrol.status='ONGOING' and patrol.expires_at<=now())) and patrol.has_battle_event and not coalesce(patrol.battle_resolved,false) for update of patrol;
 if not found then raise exception 'eligible patrol encounter not found' using errcode='P0002'; end if;
 update public.user_patrols set status='CLAIMABLE' where id=p_patrol_id and status='ONGOING';
 select array_remove(array[deck.character_1_id::text,deck.character_2_id::text,deck.character_3_id::text,deck.character_4_id::text,deck.character_5_id::text],null) into v_ids from public.pvp_defense_decks deck where deck.user_id=v_uid;
 if coalesce(cardinality(v_ids),0)=0 then select array[owned.id::text] into v_ids from public.user_characters owned where owned.user_id=v_uid and owned.character_id=v_patrol.character_id order by owned.created_at limit 1; end if;
 v_player:=public.build_server_battle_snapshot(v_uid,v_ids,'PLAYER'); v_enemy:=public.canonical_quest_enemy_snapshot(coalesce(v_patrol.course_id,v_patrol.quest_id));
 if coalesce(jsonb_array_length(v_enemy),0)<>5 then raise exception 'canonical quest encounter must contain five members' using errcode='23514'; end if;
 v_seed:=floor(random()*2147483646)::bigint+1;
 insert into public.battle_replay_sessions(requester_user_id,battle_mode,source_reference_id,tactic_id,random_seed,player_snapshot,enemy_snapshot,resolution_authority) values(v_uid,'QUEST',p_patrol_id,p_tactic_id,v_seed,v_player,v_enemy,'PATROL_SERVER') returning id into v_replay;
 return jsonb_build_object('replay_session_id',v_replay,'player_snapshot',v_player,'enemy_snapshot',v_enemy);
end $$;

create or replace function public.claim_patrol_rewards(p_patrol_id uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_patrol record; v_first boolean:=false; v_item record; v_items jsonb:='[]'::jsonb; v_xp jsonb; v_total_xp integer;
begin
 if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if;
 select patrol.*,quest.display_name,quest.cash_reward,quest.user_exp,quest.first_clear_user_exp,quest.reward_pool_id,quest.first_clear_reward_pool_id into v_patrol from public.user_patrols patrol join public.canonical_quest_master quest on quest.version='2026-08-22' and quest.quest_id=coalesce(patrol.course_id,patrol.quest_id) and quest.is_production_enabled where patrol.id=p_patrol_id and patrol.user_id=v_uid for update of patrol;
 if not found then raise exception 'patrol not found' using errcode='P0002'; end if;
 if v_patrol.status='COMPLETED' then raise exception 'patrol rewards already claimed' using errcode='23505'; end if;
 if v_patrol.status<>'CLAIMABLE' and v_patrol.expires_at>now() then raise exception 'patrol is not complete' using errcode='23514'; end if;
 if v_patrol.has_battle_event and not coalesce(v_patrol.battle_resolved,false) then raise exception 'patrol battle must be resolved before claiming rewards' using errcode='23514'; end if;
 insert into public.user_quest_first_clears(user_id,quest_id) values(v_uid,coalesce(v_patrol.course_id,v_patrol.quest_id)) on conflict do nothing returning true into v_first;
 v_first:=coalesce(v_first,false); v_total_xp:=v_patrol.user_exp+case when v_first then v_patrol.first_clear_user_exp else 0 end;
 insert into public.presents(user_id,item_id,quantity,message,status,expire_at) values(v_uid,'CASH',v_patrol.cash_reward,'クエスト報酬: '||v_patrol.display_name,'UNCLAIMED',now()+interval '24 hours');
 for v_item in select * from public.canonical_quest_reward_pool_items item where item.version='2026-08-22' and (item.reward_pool_id=v_patrol.reward_pool_id or (v_first and item.reward_pool_id=v_patrol.first_clear_reward_pool_id)) order by item.reward_pool_id,item.roll_index loop
  if floor(random()*10000)::integer<v_item.probability_bp then insert into public.presents(user_id,item_id,quantity,message,status,expire_at) values(v_uid,v_item.item_id,v_item.quantity,case when v_item.reward_pool_id=v_patrol.first_clear_reward_pool_id then 'クエスト初回報酬: ' else 'クエストドロップ: ' end||v_patrol.display_name,'UNCLAIMED',now()+interval '24 hours'); v_items:=v_items||jsonb_build_array(jsonb_build_object('item_id',v_item.item_id,'quantity',v_item.quantity)); end if;
 end loop;
 v_xp:=public.apply_user_xp(v_uid,v_total_xp);
 update public.user_patrols set status='COMPLETED',rewards_accrued=jsonb_build_object('course_name',v_patrol.display_name,'cash',v_patrol.cash_reward,'xp',v_total_xp,'items',v_items,'first_clear',v_first) where id=p_patrol_id;
 perform public.evaluate_mission_progress(v_uid,'PATROL_CLEAR',1);
 return jsonb_build_object('status','success','patrol_id',p_patrol_id,'course_name',v_patrol.display_name,'cash',v_patrol.cash_reward,'xp',v_total_xp,'items',v_items,'first_clear',v_first,'level',v_xp->'level','current_xp',v_xp->'xp','leveled_up',v_xp->'leveled_up');
end $$;

alter table public.canonical_quest_master enable row level security; alter table public.canonical_quest_reward_pool_items enable row level security; alter table public.canonical_quest_encounter_master enable row level security; alter table public.user_quest_first_clears enable row level security;
revoke all on public.canonical_quest_master,public.canonical_quest_reward_pool_items,public.canonical_quest_encounter_master from public,anon; grant select on public.canonical_quest_master,public.canonical_quest_reward_pool_items,public.canonical_quest_encounter_master to authenticated;
revoke all on function public.start_patrol(text,text),public.complete_patrol_instantly(uuid,uuid,text),public.canonical_quest_enemy_snapshot(text),public.create_patrol_battle_replay(uuid,text),public.claim_patrol_rewards(uuid) from public,anon;
grant execute on function public.start_patrol(text,text),public.complete_patrol_instantly(uuid,uuid,text),public.create_patrol_battle_replay(uuid,text),public.claim_patrol_rewards(uuid) to authenticated; grant execute on function public.canonical_quest_enemy_snapshot(text) to service_role;

do $$ begin
 if (select count(*) from public.canonical_quest_master where version='2026-08-22' and is_production_enabled)<>21 then raise exception 'Canonical Quest count mismatch'; end if;
 if (select count(*) from public.canonical_quest_encounter_master where version='2026-08-22' and is_production_enabled)<>21 then raise exception 'Canonical Encounter count mismatch'; end if;
 if exists(select 1 from public.canonical_quest_master where unlock_condition<>'NONE' or enemy_encounter_id is null) then raise exception 'Canonical Quest unresolved field'; end if;
 if exists(select 1 from public.canonical_quest_encounter_master where jsonb_array_length(members)<>5 or normal_attack_power_bp<>8000) then raise exception 'Canonical Encounter contract mismatch'; end if;
end $$;
commit; notify pgrst,'reload schema';
`;
fs.writeFileSync("supabase/migrations/20260822000181_quest_production_foundation.sql", sql);
console.log("Generated migration 00181.");
