import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";

const levelMaster = JSON.parse(await readFile("src/domain/gameplay/canonical/data/user_level_progression_20260822.json", "utf8"));
const resourceMaster = JSON.parse(await readFile("src/domain/gameplay/canonical/data/action_resources_20260822.json", "utf8"));
const itemMaster = JSON.parse(await readFile("src/domain/gameplay/canonical/data/items_20260822.json", "utf8"));
const outputPath = "supabase/migrations/20260822000179_user_level_recovery_ticket_final.sql";

assert.equal(levelMaster.levels.length, 100);
assert.equal(levelMaster.maxUserLevel, 100);
assert.equal(levelMaster.levels.at(-1).requiredExp, 0);
for (const [level, cumulative] of [[8,1750],[10,3050],[20,28050],[30,120550],[50,708050],[75,2712750],[100,6858050]]) {
  assert.equal(levelMaster.levels[level - 1].cumulativeExp, cumulative);
}
assert.equal(resourceMaster.recoveryItems.PVP_POINT_TICKET.amount, 1);
assert.equal(resourceMaster.recoveryItems.RAID_POINT_TICKET.amount, 1);
const ticketItems = itemMaster.items.filter((item) => ["PVP_POINT_TICKET", "RAID_POINT_TICKET"].includes(item.id));
assert.equal(ticketItems.length, 2);
assert(ticketItems.every((item) => item.runtimeUsage.effectValue === 1));

const levelJson = JSON.stringify(levelMaster.levels);
const sql = `-- Generated by scripts/generate_user_level_final_db_migration.mjs. Do not hand-edit master values.
begin;

alter table public.canonical_user_level_master drop constraint if exists canonical_user_level_master_required_exp_check;
alter table public.canonical_user_level_master add constraint canonical_user_level_master_required_exp_check check(required_exp >= 0);

insert into public.canonical_user_level_master(version,level,required_exp,cumulative_exp,unlock_keys)
select '2026-08-22',level,"requiredExp","cumulativeExp","unlockKeys"
from jsonb_to_recordset($levels$${levelJson}$levels$::jsonb)
 as row(level integer,"requiredExp" integer,"cumulativeExp" integer,"unlockKeys" jsonb)
on conflict(version,level) do update set required_exp=excluded.required_exp,cumulative_exp=excluded.cumulative_exp,unlock_keys=excluded.unlock_keys;

insert into public.user_level_master(level,next_xp)
select level,"requiredExp" from jsonb_to_recordset($levels$${levelJson}$levels$::jsonb) as row(level integer,"requiredExp" integer)
on conflict(level) do update set next_xp=excluded.next_xp;

update public.canonical_item_master set runtime_usage=jsonb_set(runtime_usage,'{effectValue}','1'::jsonb,true),
 description=case item_id when 'PVP_POINT_TICKET' then 'PvP Pointを1回復します。' else 'Raid Pointを1回復します。' end
where version='2026-08-22' and item_id in ('PVP_POINT_TICKET','RAID_POINT_TICKET');

create or replace function public.apply_user_xp(p_user_id uuid,p_xp_amount integer)
returns jsonb language plpgsql security definer set search_path=public as \$\$
declare v_level integer; v_xp integer; v_required integer; v_leveled boolean:=false;
begin
 if p_xp_amount<0 then raise exception 'XP amount must not be negative' using errcode='22023'; end if;
 select level,xp into v_level,v_xp from public.users where id=p_user_id for update;
 if not found then raise exception 'user not found' using errcode='P0002'; end if;
 if v_level>100 then
  return jsonb_build_object('level',v_level,'xp',v_xp,'leveled_up',false,'level_cap',100,'over_cap_audit',true);
 end if;
 if v_level=100 then
  update public.users set xp=0 where id=p_user_id;
  return jsonb_build_object('level',100,'xp',0,'leveled_up',false,'level_cap',100);
 end if;
 v_xp:=greatest(coalesce(v_xp,0),0)+p_xp_amount;
 while v_level<100 loop
  select required_exp into v_required from public.canonical_user_level_master where version='2026-08-22' and level=v_level;
  exit when v_required is null or v_required=0 or v_xp<v_required;
  v_xp:=v_xp-v_required; v_level:=v_level+1; v_leveled:=true;
 end loop;
 if v_level=100 then v_xp:=0; end if;
 update public.users set level=v_level,xp=v_xp where id=p_user_id;
 return jsonb_build_object('level',v_level,'xp',v_xp,'leveled_up',v_leveled,'level_cap',100);
end \$\$;

create or replace function public.use_action_resource_ticket(p_item_id text)
returns jsonb language plpgsql security definer set search_path=public as \$\$
declare v_user_id uuid:=auth.uid(); v_points integer; v_quantity integer; v_resource text;
begin
 if v_user_id is null then raise exception 'authentication required' using errcode='42501'; end if;
 if p_item_id not in ('PVP_POINT_TICKET','RAID_POINT_TICKET') then raise exception 'unsupported action resource ticket' using errcode='22023'; end if;
 perform public.sync_and_recover_vitality_and_pvp_points(v_user_id);
 if p_item_id='PVP_POINT_TICKET' then
  select pvp_points into v_points from public.users where id=v_user_id for update; v_resource:='PVP_POINT';
 else
  select raid_points into v_points from public.users where id=v_user_id for update; v_resource:='RAID_POINT';
 end if;
 if not found then raise exception 'player profile is not initialized' using errcode='P0002'; end if;
 if v_points>=5 then raise exception 'action resource is already at maximum' using errcode='23514'; end if;
 update public.user_items set quantity=quantity-1 where user_id=v_user_id and item_id=p_item_id and quantity>=1 returning quantity into v_quantity;
 if not found then raise exception 'action resource ticket is not available' using errcode='23514'; end if;
 if p_item_id='PVP_POINT_TICKET' then update public.users set pvp_points=pvp_points+1 where id=v_user_id returning pvp_points into v_points;
 else update public.users set raid_points=raid_points+1 where id=v_user_id returning raid_points into v_points; end if;
 return jsonb_build_object('status','success','item_id',p_item_id,'quantity',v_quantity,'resource',v_resource,'points',v_points);
end \$\$;

do \$\$ declare v_over_cap bigint; begin
 select count(*) into v_over_cap from public.users where level>100;
 if v_over_cap>0 then raise warning 'USER_LEVEL_OVER_CAP_AUDIT_REQUIRED: % users',v_over_cap; end if;
 if (select count(*) from public.canonical_user_level_master where version='2026-08-22')<>100 then raise exception 'Canonical User Level count mismatch'; end if;
 if (select cumulative_exp from public.canonical_user_level_master where version='2026-08-22' and level=100)<>6858050 then raise exception 'Lv100 cumulative EXP mismatch'; end if;
end \$\$;

revoke all on function public.use_action_resource_ticket(text) from public,anon;
grant execute on function public.use_action_resource_ticket(text) to authenticated;

commit;
notify pgrst,'reload schema';
`;
await writeFile(outputPath, sql);
console.log(`Generated ${outputPath}`);
