import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { EQUIPMENTS_MASTER_DATA } from "../src/utils/equipments_master_data.ts";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(
  scriptDir,
  "../supabase/migrations/20260812000118_patrol_equipment_snapshot.sql",
);

const sqlString = (value) => `'${String(value).replaceAll("'", "''")}'`;
const nullableString = (value) => (value == null ? "null" : sqlString(value));

const values = EQUIPMENTS_MASTER_DATA.map((item) =>
  `  (${[
    sqlString(item.id),
    sqlString(item.name),
    sqlString(item.rarity),
    sqlString(item.slot_type),
    item.hp,
    item.atk,
    item.def,
    item.spd,
    item.luk,
    item.is_exclusive,
    nullableString(item.exclusive_character_id),
  ].join(", ")})`,
).join(",\n");

const sql = `-- Generated by scripts/generate_battle_equipment_master.mjs.
-- Open Beta M2-4a: server-authoritative equipment stats in patrol snapshots.

create table if not exists public.equipment_battle_master (
  equipment_id text primary key,
  display_name text not null,
  rarity text not null check (rarity in ('N', 'R', 'SR', 'SSR')),
  slot_type text not null check (slot_type in ('WEAPON', 'HEAD', 'BODY', 'LEGS', 'ACCESSORY')),
  hp integer not null default 0,
  atk integer not null default 0,
  def integer not null default 0,
  spd integer not null default 0,
  luk integer not null default 0,
  is_exclusive boolean not null default false,
  exclusive_character_id text
);

insert into public.equipment_battle_master (
  equipment_id, display_name, rarity, slot_type,
  hp, atk, def, spd, luk, is_exclusive, exclusive_character_id
)
values
${values}
on conflict (equipment_id) do update set
  display_name = excluded.display_name,
  rarity = excluded.rarity,
  slot_type = excluded.slot_type,
  hp = excluded.hp,
  atk = excluded.atk,
  def = excluded.def,
  spd = excluded.spd,
  luk = excluded.luk,
  is_exclusive = excluded.is_exclusive,
  exclusive_character_id = excluded.exclusive_character_id;

create or replace function public.create_patrol_battle_replay(
  p_patrol_id uuid,
  p_tactic_id text default 'ATTACK_PRIORITY'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_patrol record;
  v_deck record;
  v_player_snapshot jsonb;
  v_enemy_snapshot jsonb;
  v_replay_id uuid;
  v_server_seed bigint;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_tactic_id not in ('ATTACK_PRIORITY', 'HEAL_PRIORITY', 'SKILL_PRIORITY', 'BALANCED', 'WEAKNESS_FOCUS') then
    raise exception 'invalid tactic' using errcode = '22023';
  end if;

  select patrol.*, npc.id as npc_id, npc.npc_name, npc.enemy_data
  into v_patrol
  from public.user_patrols patrol
  join public.patrol_npcs npc on npc.quest_id = coalesce(patrol.course_id, patrol.quest_id)
  where patrol.id = p_patrol_id
    and patrol.user_id = v_user_id
    and (
      patrol.status = 'CLAIMABLE'
      or (patrol.status = 'ONGOING' and patrol.expires_at <= now())
    )
    and patrol.has_battle_event = true
    and coalesce(patrol.battle_resolved, false) = false
  order by npc.id
  limit 1
  for update of patrol;

  if not found then
    raise exception 'eligible patrol encounter not found' using errcode = 'P0002';
  end if;

  update public.user_patrols
  set status = 'CLAIMABLE'
  where id = p_patrol_id and status = 'ONGOING';

  select deck.* into v_deck
  from public.pvp_defense_decks deck
  where deck.user_id = v_user_id;

  with deck_requested(character_id, ordinality) as (
    select value, ordinality
    from unnest(array[
      v_deck.character_1_id, v_deck.character_2_id, v_deck.character_3_id,
      v_deck.character_4_id, v_deck.character_5_id
    ]) with ordinality as picked(value, ordinality)
    where value is not null
  ), requested(character_id, ordinality) as (
    select character_id, ordinality from deck_requested
    union all
    select owned.id::text, 1
    from public.user_characters owned
    where owned.user_id = v_user_id
      and owned.character_id = v_patrol.character_id
      and not exists (select 1 from deck_requested)
      and owned.id = (
        select fallback.id from public.user_characters fallback
        where fallback.user_id = v_user_id
          and fallback.character_id = v_patrol.character_id
        order by fallback.created_at
        limit 1
      )
  ), canonical_base as (
    select owned.id, owned.character_id, owned.level, owned.awakening_level,
           requested.ordinality, master.display_name, master.alignment,
           floor((growth.base_hp + (owned.level - 1) * growth.hp_gain + coalesce(awake.hp_bonus, 0)) * master.rarity_multiplier)::integer as hp,
           floor((growth.base_atk + (owned.level - 1) * growth.atk_gain + coalesce(awake.atk_bonus, 0)) * master.rarity_multiplier)::integer as atk,
           floor((growth.base_def + (owned.level - 1) * growth.def_gain + coalesce(awake.def_bonus, 0)) * master.rarity_multiplier)::integer as def,
           floor((growth.base_spd + floor((owned.level - 1) * growth.spd_gain) + coalesce(awake.spd_bonus, 0)) * master.rarity_multiplier)::integer as spd,
           floor((growth.base_luk + floor((owned.level - 1) * growth.luk_gain) + coalesce(awake.luk_bonus, 0)) * master.rarity_multiplier)::integer as luk
    from requested
    join public.user_characters owned
      on owned.user_id = v_user_id and owned.id::text = requested.character_id
    join public.character_battle_master master on master.character_id = owned.character_id
    join public.character_growth_patterns growth on growth.pattern_id = master.growth_pattern_id
    left join public.character_awakening_master awake on awake.awakening_level = owned.awakening_level
  ), canonical as (
    select base.*,
      coalesce(equipment.hp, 0)::integer as equipment_hp,
      coalesce(equipment.atk, 0)::integer as equipment_atk,
      coalesce(equipment.def, 0)::integer as equipment_def,
      coalesce(equipment.spd, 0)::integer as equipment_spd,
      coalesce(equipment.luk, 0)::integer as equipment_luk,
      coalesce(equipment.loadout, '[]'::jsonb) as equipment_loadout,
      coalesce(skills.loadout, '[]'::jsonb) as equipped_skill_refs
    from canonical_base base
    left join lateral (
      select
        sum(floor(master.hp * ((case when greatest(least(coalesce(owned.level, 1), 100), 1) <= 50 then 0.1 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 1) * 0.5 / 49 else 0.6 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 50) * 0.4 / 50 end) + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as hp,
        sum(floor(master.atk * ((case when greatest(least(coalesce(owned.level, 1), 100), 1) <= 50 then 0.1 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 1) * 0.5 / 49 else 0.6 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 50) * 0.4 / 50 end) + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as atk,
        sum(floor(master.def * ((case when greatest(least(coalesce(owned.level, 1), 100), 1) <= 50 then 0.1 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 1) * 0.5 / 49 else 0.6 + (greatest(least(coalesce(owned.level, 1), 100), 1) - 50) * 0.4 / 50 end) + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as def,
        sum(master.spd) as spd,
        sum(master.luk) as luk,
        jsonb_agg(jsonb_build_object(
          'instanceId', owned.id,
          'equipmentId', master.equipment_id,
          'slotIndex', owned.slot_index,
          'level', greatest(coalesce(owned.level, 1), 1),
          'plusValue', greatest(coalesce(owned.plus_val, 0), 0)
        ) order by owned.slot_index, owned.id) as loadout
      from public.user_equipments owned
      join public.equipment_battle_master master
        on master.equipment_id = coalesce(nullif(owned.equipment_id, ''), owned.equipment_master_id)
      where owned.user_id = v_user_id
        and owned.equipped_character_id = base.id::text
        and (not master.is_exclusive or master.exclusive_character_id = base.character_id)
    ) equipment on true
    left join lateral (
      select jsonb_agg(jsonb_build_object(
        'skillId', owned.skill_card_id,
        'slotIndex', owned.slot_index,
        'plusValue', greatest(least(coalesce(owned.plus_val, 0), 10), 0),
        'effectScale', case
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 3
            then 1 + greatest(least(coalesce(owned.plus_val, 0), 10), 0) * 0.05
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 6
            then 1.15 + (greatest(least(coalesce(owned.plus_val, 0), 10), 0) - 3) * 0.04
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 9
            then 1.27 + (greatest(least(coalesce(owned.plus_val, 0), 10), 0) - 6) * 0.03
          else 1.41
        end
      ) order by owned.slot_index, owned.skill_card_id) as loadout
      from public.user_skills owned
      where owned.user_id = v_user_id
        and owned.equipped_character_id = base.id::text
    ) skills on true
  )
  select jsonb_agg(jsonb_build_object(
    'id', 'ally_' || canonical.character_id,
    'name', canonical.display_name,
    'team', 'PLAYER',
    'alignment', canonical.alignment,
    'stats', jsonb_build_object(
      'hp', greatest(canonical.hp + canonical.equipment_hp, 1),
      'atk', greatest(canonical.atk + canonical.equipment_atk, 0),
      'def', greatest(canonical.def + canonical.equipment_def, 0),
      'spd', greatest(canonical.spd + canonical.equipment_spd, 0),
      'luk', greatest(canonical.luk + canonical.equipment_luk, 0)
    ),
    'equipment', canonical.equipment_loadout,
    -- Individual target/cooldown fields do not yet exist in the approved
    -- skill master. Preserve the owned loadout for audit/replay migration,
    -- but do not invent executable effects; basic attack remains canonical.
    'equippedSkillRefs', canonical.equipped_skill_refs,
    'skills', jsonb_build_array(jsonb_build_object(
      'id', 'basic_attack_' || canonical.id::text, 'name', 'Attack',
      'kind', 'ATTACK', 'target', 'ENEMY_SINGLE', 'powerPercent', 100, 'cooldown', 0
    ))
  ) order by canonical.ordinality)
  into v_player_snapshot
  from canonical;

  if coalesce(jsonb_array_length(v_player_snapshot), 0) = 0 then
    raise exception 'battle formation has no supported owned character' using errcode = '23514';
  end if;

  v_enemy_snapshot := jsonb_build_array(jsonb_build_object(
    'id', 'enemy_' || v_patrol.npc_id,
    'name', v_patrol.npc_name,
    'team', 'ENEMY',
    'alignment', 'CHAOS',
    'stats', jsonb_build_object(
      'hp', greatest(coalesce((v_patrol.enemy_data ->> 'hp')::integer, 1), 1),
      'atk', greatest(coalesce((v_patrol.enemy_data ->> 'atk')::integer, 1), 0),
      'def', greatest(coalesce((v_patrol.enemy_data ->> 'def')::integer, 0), 0),
      'spd', greatest(coalesce((v_patrol.enemy_data ->> 'spd')::integer, 1), 0),
      'luk', greatest(coalesce((v_patrol.enemy_data ->> 'luk')::integer, 0), 0)
    ),
    'skills', jsonb_build_array(jsonb_build_object(
      'id', 'npc_basic_attack', 'name', 'Attack', 'kind', 'ATTACK',
      'target', 'ENEMY_SINGLE', 'powerPercent', 100, 'cooldown', 0
    ))
  ));

  v_server_seed := floor(random() * 2147483646)::bigint + 1;
  insert into public.battle_replay_sessions (
    requester_user_id, battle_mode, source_reference_id, tactic_id,
    random_seed, player_snapshot, enemy_snapshot, resolution_authority
  ) values (
    v_user_id, 'QUEST', p_patrol_id, p_tactic_id,
    v_server_seed, v_player_snapshot, v_enemy_snapshot, 'PATROL_SERVER'
  ) returning id into v_replay_id;

  return jsonb_build_object(
    'replay_session_id', v_replay_id,
    'player_snapshot', v_player_snapshot,
    'enemy_snapshot', v_enemy_snapshot
  );
end;
$$;

revoke all on table public.equipment_battle_master from public, anon, authenticated;
revoke all on function public.create_patrol_battle_replay(uuid, text) from public, anon;
grant execute on function public.create_patrol_battle_replay(uuid, text) to authenticated;

notify pgrst, 'reload schema';
`;

writeFileSync(outputPath, sql, "utf8");
console.log(`Wrote ${EQUIPMENTS_MASTER_DATA.length} equipment rows to ${outputPath}`);
