import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const readText = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const items = readJson("src/domain/gameplay/canonical/data/items_20260822.json");
const login = readJson("src/domain/gameplay/canonical/data/login_bonus_20260822.json");
const supply = readJson("src/domain/gameplay/canonical/data/reward_supply_20260822.json");

const legacyIds = [
  "LAW_OF_STRIFE", "ITEM_STAMINA_01", "ITEM_EXP_DRINK", "TRAINING_MANUAL",
  "EXCLUSIVE_CONTRACT", "EQUIP_LB_HAMMER", "SKILL_LB_BOOK", "NORMAL_GACHA_TICKET",
];
const itemIds = new Set(items.items.map((item) => item.id));
if (itemIds.size !== items.items.length || items.items.length !== 18) throw new Error("Canonical Item Master must contain 18 unique items.");
if (items.items.some((item) => legacyIds.includes(item.id))) throw new Error("Legacy item ID found in Canonical Item Master.");
if (login.rewards.length !== 30 || login.rewards.map((reward) => reward.day).join(",") !== Array.from({ length: 30 }, (_, index) => index + 1).join(",")) {
  throw new Error("Login Bonus must contain exactly days 1..30.");
}
for (const reward of login.rewards) {
  if (!["CASH", "DIAMOND"].includes(reward.rewardItemId) && !itemIds.has(reward.rewardItemId)) throw new Error(`Unknown Login Bonus item ${reward.rewardItemId}`);
  if (legacyIds.includes(reward.rewardItemId)) throw new Error(`Legacy Login Bonus item ${reward.rewardItemId}`);
}

const effectValue = new Map(items.items.map((item) => [item.id, Number(item.runtimeUsage?.effectValue || 0)]));
const aggregate = login.rewards.reduce((result, reward) => {
  if (reward.rewardItemId === "CASH" || reward.rewardItemId === "DIAMOND" || reward.rewardItemId === "SKILL_MANUAL" || reward.rewardItemId === "EQUIP_LB_PART" || reward.rewardItemId === "ENERGY_DRINK" || reward.rewardItemId === "AWAKENING_BOOK") {
    result[reward.rewardItemId] = (result[reward.rewardItemId] || 0) + reward.rewardQty;
  }
  if (reward.rewardItemId.startsWith("SPECIAL_TICKET_")) {
    result[reward.rewardItemId] = (result[reward.rewardItemId] || 0) + reward.rewardQty;
    result.SPECIAL_TICKET = (result.SPECIAL_TICKET || 0) + reward.rewardQty;
  }
  if (reward.rewardItemId.startsWith("CHAR_EXP_")) result.CHARACTER_EXP = (result.CHARACTER_EXP || 0) + reward.rewardQty * effectValue.get(reward.rewardItemId);
  if (reward.rewardItemId.startsWith("EQUIP_EXP_")) result.EQUIPMENT_EXP = (result.EQUIPMENT_EXP || 0) + reward.rewardQty * effectValue.get(reward.rewardItemId);
  return result;
}, {});
for (const [key, expected] of Object.entries(login.expectedAggregate)) {
  if (aggregate[key] !== expected) throw new Error(`Login Bonus aggregate mismatch for ${key}: ${aggregate[key]} != ${expected}`);
}

function extractFunction(relative, functionName, nextMarker = null) {
  const source = readText(relative);
  const start = source.toLowerCase().indexOf(`create or replace function public.${functionName}`);
  if (start < 0) throw new Error(`Function ${functionName} not found in ${relative}`);
  let end;
  if (nextMarker) {
    end = source.toLowerCase().indexOf(`create or replace function public.${nextMarker}`, start + 1);
  } else {
    end = source.indexOf("$$;", start) + 3;
  }
  if (end <= start) throw new Error(`Function boundary for ${functionName} not found`);
  return source.slice(start, end).trim();
}

const characterGacha = extractFunction(
  "supabase/migrations/20260821000173_mission_production_master.sql",
  "execute_character_gacha",
  "execute_asset_gacha",
).replaceAll("LAW_OF_STRIFE", "AWAKENING_BOOK");
const tutorialGacha = extractFunction(
  "supabase/migrations/20260818000161_m9x_cold_start_social_foundation.sql",
  "execute_tutorial_character_gacha",
  "complete_current_tutorial_formation",
).replaceAll("LAW_OF_STRIFE", "AWAKENING_BOOK");
const pityExchange = extractFunction(
  "supabase/migrations/20260805000007_exchange_pity_reward_rpc.sql",
  "exchange_pity_reward",
).replaceAll("LAW_OF_STRIFE", "AWAKENING_BOOK").replaceAll("TRAINING_MANUAL", "SKILL_MANUAL");

const sqlItems = JSON.stringify(items.items);
const sqlSupply = JSON.stringify(supply.sources);
const loginRows = login.rewards.map((reward) => {
  const item = items.items.find((entry) => entry.id === reward.rewardItemId);
  const name = reward.rewardItemId === "CASH" ? "CASH" : reward.rewardItemId === "DIAMOND" ? "ダイヤ" : item.name;
  const featured = [5, 12, 15, 20, 26, 29, 30].includes(reward.day);
  return `(${reward.day}, '${reward.rewardItemId}', ${reward.rewardQty}, '${name.replaceAll("'", "''")} ${reward.rewardQty}', ${featured})`;
}).join(",\n  ");

const sql = `-- Generated by scripts/generate_economy_foundation_db_migration.mjs. Do not hand-edit seed values.
begin;

create table if not exists public.canonical_item_master (
  version text not null,
  item_id text not null,
  display_name text not null,
  category text not null,
  description text not null,
  stackable boolean not null,
  max_stack integer,
  usage_type text not null,
  source_categories jsonb not null default '[]'::jsonb,
  expiry_policy text not null,
  runtime_usage jsonb not null default '{}'::jsonb,
  asset_path text,
  is_production_enabled boolean not null,
  primary key (version, item_id)
);

alter table public.canonical_item_master enable row level security;
revoke all on public.canonical_item_master from anon, authenticated;
grant select on public.canonical_item_master to authenticated;
drop policy if exists canonical_item_master_read on public.canonical_item_master;
create policy canonical_item_master_read on public.canonical_item_master for select to authenticated using (is_production_enabled);

insert into public.canonical_item_master(version,item_id,display_name,category,description,stackable,max_stack,usage_type,source_categories,expiry_policy,runtime_usage,asset_path,is_production_enabled)
select '${items.version}', id, name, category, description, stackable, "maxStack", "usageType", "sourceCategory", "expiryPolicy", "runtimeUsage", "assetPath", "isProductionEnabled"
from jsonb_to_recordset($items$${sqlItems}$items$::jsonb) as row(id text,name text,category text,description text,stackable boolean,"maxStack" integer,"usageType" text,"sourceCategory" jsonb,"expiryPolicy" text,"runtimeUsage" jsonb,"assetPath" text,"isProductionEnabled" boolean)
on conflict(version,item_id) do update set display_name=excluded.display_name,category=excluded.category,description=excluded.description,stackable=excluded.stackable,max_stack=excluded.max_stack,usage_type=excluded.usage_type,source_categories=excluded.source_categories,expiry_policy=excluded.expiry_policy,runtime_usage=excluded.runtime_usage,asset_path=excluded.asset_path,is_production_enabled=excluded.is_production_enabled;

create table if not exists public.canonical_reward_supply_sources (
  version text not null,
  source text not null,
  status text not null check(status in ('FROZEN','CANDIDATE','PENDING_FREEZE')),
  authority text not null,
  notes text not null,
  primary key(version,source)
);
alter table public.canonical_reward_supply_sources enable row level security;
revoke all on public.canonical_reward_supply_sources from anon, authenticated;
grant select on public.canonical_reward_supply_sources to authenticated;
drop policy if exists canonical_reward_supply_sources_read on public.canonical_reward_supply_sources;
create policy canonical_reward_supply_sources_read on public.canonical_reward_supply_sources for select to authenticated using (true);
insert into public.canonical_reward_supply_sources(version,source,status,authority,notes)
select '${supply.version}', source,status,authority,notes
from jsonb_to_recordset($supply$${sqlSupply}$supply$::jsonb) as row(source text,status text,authority text,notes text)
on conflict(version,source) do update set status=excluded.status,authority=excluded.authority,notes=excluded.notes;

-- Ambiguous legacy balances are never guessed or deleted. The migration aborts before changing master/runtime state.
do $$ begin
  if exists(select 1 from public.user_items where item_id in ('ITEM_EXP_DRINK','EXCLUSIVE_CONTRACT') and quantity>0)
     or exists(select 1 from public.presents where item_id in ('ITEM_EXP_DRINK','EXCLUSIVE_CONTRACT') and status='UNCLAIMED') then
    raise exception 'AMBIGUOUS_LEGACY_ITEM_BALANCE_REQUIRES_PRODUCT_MAPPING';
  end if;
end $$;

insert into public.login_bonus_master(day_number,item_id,quantity,item_name,is_featured) values
  ${loginRows}
on conflict(day_number) do update set item_id=excluded.item_id,quantity=excluded.quantity,item_name=excluded.item_name,is_featured=excluded.is_featured;

${characterGacha}

${tutorialGacha}

${pityExchange}

do $$ begin
  if (select count(*) from public.canonical_item_master where version='${items.version}' and is_production_enabled) <> 18 then raise exception 'Canonical Item count mismatch'; end if;
  if (select count(*) from public.login_bonus_master where day_number between 1 and 30) <> 30 then raise exception 'Login Bonus count mismatch'; end if;
  if exists(select 1 from public.login_bonus_master where item_id in ('LAW_OF_STRIFE','ITEM_STAMINA_01','ITEM_EXP_DRINK','TRAINING_MANUAL','EXCLUSIVE_CONTRACT','EQUIP_LB_HAMMER','SKILL_LB_BOOK','NORMAL_GACHA_TICKET')) then raise exception 'Legacy Login Bonus item remains'; end if;
end $$;

commit;
`;

const output = path.join(root, "supabase/migrations/20260822000174_economy_foundation_canonical.sql");
fs.writeFileSync(output, sql);
console.log(`Generated ${path.relative(root, output)} with ${items.items.length} items and ${login.rewards.length} Login Bonus rows.`);
