import fs from "node:fs";

const quests = JSON.parse(fs.readFileSync("src/domain/gameplay/canonical/data/quests_20260822.json", "utf8"));
const encounters = JSON.parse(fs.readFileSync("src/domain/gameplay/canonical/data/quest_encounters_20260822.json", "utf8"));
const output = "supabase/migrations/20260822000185_quest_gameplay_v2.sql";
const sqlLiteral = (value) => `$json$${JSON.stringify(value)}$json$`;
const questRows = quests.quests.map((quest) => ({ questId:quest.questId, unlock_condition:quest.unlockCondition.type === "OPEN" ? "OPEN" : `FIRST_CLEAR:${quest.unlockCondition.questId}` }));

const sql = `-- Generated by scripts/generate_quest_gameplay_v2_db_migration.mjs. Do not hand-edit seed values.
begin;

alter table public.canonical_quest_master drop constraint if exists canonical_quest_master_unlock_condition_check;
alter table public.canonical_quest_encounter_master add column if not exists enemy_tactic text;
alter table public.canonical_quest_encounter_master drop constraint if exists canonical_quest_encounter_master_enemy_tactic_check;
alter table public.canonical_quest_encounter_master add constraint canonical_quest_encounter_master_enemy_tactic_check
 check(enemy_tactic in ('ATTACK_PRIORITY','HEAL_PRIORITY','SKILL_PRIORITY','BALANCED','WEAKNESS_FOCUS'));
alter table public.battle_replay_sessions add column if not exists enemy_tactic_id text;
alter table public.battle_replay_sessions drop constraint if exists battle_replay_sessions_enemy_tactic_check;
alter table public.battle_replay_sessions add constraint battle_replay_sessions_enemy_tactic_check
 check(enemy_tactic_id is null or enemy_tactic_id in ('ATTACK_PRIORITY','HEAL_PRIORITY','SKILL_PRIORITY','BALANCED','WEAKNESS_FOCUS'));

update public.canonical_quest_master master set unlock_condition=seed.unlock_condition
from jsonb_to_recordset(${sqlLiteral(questRows)}::jsonb) as seed("questId" text,unlock_condition text)
where master.version='2026-08-22' and master.quest_id=seed."questId";

alter table public.canonical_quest_master add constraint canonical_quest_master_unlock_condition_check
 check (unlock_condition='OPEN' or unlock_condition ~ '^FIRST_CLEAR:q_(shinjuku|shibuya|ikebukuro|roppongi|akihabara|kawasaki|yokohama)_[12]$');

insert into public.canonical_quest_encounter_master(version,encounter_id,quest_id,town_id,difficulty,members,normal_attack_power_bp,tuning_status,is_production_enabled,enemy_tactic)
select '2026-08-22',"encounterId","questId","townId",difficulty,members,"normalAttackPowerBp","tuningStatus","isProductionEnabled","enemyTactic"
from jsonb_to_recordset(${sqlLiteral(encounters.encounters)}::jsonb) as seed("encounterId" text,"questId" text,"townId" text,difficulty text,"enemyTactic" text,members jsonb,"normalAttackPowerBp" integer,"tuningStatus" text,"isProductionEnabled" boolean)
on conflict(version,encounter_id) do update set quest_id=excluded.quest_id,town_id=excluded.town_id,difficulty=excluded.difficulty,members=excluded.members,normal_attack_power_bp=excluded.normal_attack_power_bp,tuning_status=excluded.tuning_status,is_production_enabled=excluded.is_production_enabled,enemy_tactic=excluded.enemy_tactic;

create or replace function public.canonical_quest_is_unlocked(p_user_id uuid,p_quest_id text) returns boolean
language sql stable security definer set search_path=public as $$
 select case when master.unlock_condition='OPEN' then true
  when master.unlock_condition like 'FIRST_CLEAR:%' then exists(
   select 1 from public.user_quest_first_clears clear
   where clear.user_id=p_user_id and clear.quest_id=substring(master.unlock_condition from 13)
  ) else false end
 from public.canonical_quest_master master
 where master.version='2026-08-22' and master.quest_id=p_quest_id and master.is_production_enabled
$$;

create or replace function public.get_canonical_quest_progression() returns jsonb
language sql stable security definer set search_path=public as $$
 select coalesce(jsonb_agg(jsonb_build_object(
  'quest_id',master.quest_id,'unlock_condition',master.unlock_condition,
  'is_unlocked',public.canonical_quest_is_unlocked(auth.uid(),master.quest_id),
  'is_first_cleared',exists(select 1 from public.user_quest_first_clears clear where clear.user_id=auth.uid() and clear.quest_id=master.quest_id),
  'enemy_tactic',encounter.enemy_tactic,'enemy_member_count',jsonb_array_length(encounter.members),
  'enemy_members',encounter.members,'recommended_level',(encounter.members->0->>'level')::integer,
  'enemy_attributes',(select jsonb_agg(distinct character.attribute) from jsonb_array_elements(encounter.members) member join public.canonical_character_master character on character.version='2026-08-21' and character.character_id=member->>'characterId'),
  'recommended_power',(select sum(stats.hp+stats.atk+stats.def) from jsonb_array_elements(encounter.members) member cross join lateral public.canonical_character_stats(member->>'characterId',(member->>'level')::integer,(member->>'awakening')::integer) stats)
 ) order by master.display_order),'[]'::jsonb)
 from public.canonical_quest_master master join public.canonical_quest_encounter_master encounter
 on encounter.version=master.version and encounter.encounter_id=master.enemy_encounter_id
 where master.version='2026-08-22' and master.is_production_enabled
$$;

create or replace function public.start_patrol(p_course_id text,p_character_id text) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_character_id text; v_q record; v_id uuid; v_active integer; v_vitality integer;
begin
 if v_user_id is null then raise exception 'authentication required' using errcode='42501'; end if;
 select * into v_q from public.canonical_quest_master where version='2026-08-22' and quest_id=p_course_id and is_production_enabled;
 if not found then raise exception 'quest not found' using errcode='23503'; end if;
 if not public.canonical_quest_is_unlocked(v_user_id,p_course_id) then raise exception 'quest is locked' using errcode='23514'; end if;
 if not exists(select 1 from public.canonical_quest_encounter_master where version='2026-08-22' and encounter_id=v_q.enemy_encounter_id and is_production_enabled) then raise exception 'quest encounter not found' using errcode='23503'; end if;
 select owned.character_id into v_character_id from public.user_characters owned where owned.user_id=v_user_id and (owned.id::text=p_character_id or owned.character_id=p_character_id) order by (owned.id::text=p_character_id) desc limit 1;
 if v_character_id is null then raise exception 'character is not owned' using errcode='23503'; end if;
 select count(*) into v_active from public.user_patrols where user_id=v_user_id and status<>'COMPLETED';
 if v_active>=5 then raise exception 'all dispatch slots are occupied' using errcode='23514'; end if;
 if exists(select 1 from public.user_patrols where user_id=v_user_id and character_id=v_character_id and status<>'COMPLETED') then raise exception 'character is already dispatched' using errcode='23505'; end if;
 perform public.sync_and_recover_vitality_and_pvp_points(v_user_id);
 select vitality into v_vitality from public.users where id=v_user_id for update;
 if coalesce(v_vitality,0)<v_q.vitality_cost then raise exception 'insufficient vitality' using errcode='23514'; end if;
 insert into public.user_patrols(user_id,course_id,character_id,started_at,expires_at,status,has_battle_event,battle_resolved)
 values(v_user_id,p_course_id,v_character_id,now(),now()+v_q.duration_sec*interval '1 second','ONGOING',true,false) returning id into v_id;
 update public.users set vitality=vitality-v_q.vitality_cost,vitality_last_recovered_at=case when vitality>=100 then now() else vitality_last_recovered_at end where id=v_user_id;
 return jsonb_build_object('status','success','patrol_id',v_id,'has_battle',true,'duration_seconds',v_q.duration_sec,'cost_vitality',v_q.vitality_cost,'remaining_vitality',v_vitality-v_q.vitality_cost);
end $$;

create or replace function public.canonical_quest_enemy_snapshot(p_quest_id text) returns jsonb
language sql stable security definer set search_path=public as $$
 with encounter as (select * from public.canonical_quest_encounter_master where version='2026-08-22' and quest_id=p_quest_id and is_production_enabled),
 members as (select encounter.*,value member,ordinality from encounter,jsonb_array_elements(encounter.members) with ordinality),
 resolved as (
  select members.encounter_id,members.ordinality,members.member,master.display_name,master.attribute,stats.*,
   coalesce((select jsonb_agg(jsonb_build_object('id',skill.skill_id,'name',skill.display_name,'activationType',skill.activation_type,'cooldown',skill.cooldown,'availableFromRound',skill.available_from_round,'target',skill.target,'effects',skill.effects,'exclusiveCharacterId',skill.exclusive_character_id) order by loadout.ordinality)
    from jsonb_array_elements_text(members.member->'skillLoadout') with ordinality loadout(skill_id,ordinality)
    join public.canonical_skill_master skill on skill.version='2026-08-21' and skill.skill_id=loadout.skill_id),'[]'::jsonb) skills
  from members join public.canonical_character_master master on master.version='2026-08-21' and master.character_id=members.member->>'characterId'
  cross join lateral public.canonical_character_stats(members.member->>'characterId',(members.member->>'level')::integer,(members.member->>'awakening')::integer) stats
 )
 select jsonb_agg(jsonb_build_object('id','enemy_'||encounter_id||'_'||ordinality,'characterId',member->>'characterId','name',display_name,'team','ENEMY','alignment',attribute,'level',(member->>'level')::integer,'awakeningLevel',(member->>'awakening')::integer,'stats',jsonb_build_object('hp',hp,'atk',atk,'def',def,'spd',spd,'luk',luk),'equipment','[]'::jsonb,'equippedSkillRefs',member->'skillLoadout','skills',skills) order by ordinality) from resolved
$$;

create or replace function public.create_patrol_battle_replay(p_patrol_id uuid,p_tactic_id text default 'ATTACK_PRIORITY') returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_patrol record; v_ids text[]; v_player jsonb; v_enemy jsonb; v_replay uuid; v_seed bigint; v_tactic text; v_expected integer;
begin
 if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if;
 if p_tactic_id not in ('ATTACK_PRIORITY','HEAL_PRIORITY','SKILL_PRIORITY','BALANCED','WEAKNESS_FOCUS') then raise exception 'invalid tactic' using errcode='22023'; end if;
 select patrol.*,encounter.enemy_tactic,jsonb_array_length(encounter.members) expected_members into v_patrol
 from public.user_patrols patrol join public.canonical_quest_master quest on quest.version='2026-08-22' and quest.quest_id=coalesce(patrol.course_id,patrol.quest_id) and quest.is_production_enabled
 join public.canonical_quest_encounter_master encounter on encounter.version=quest.version and encounter.encounter_id=quest.enemy_encounter_id and encounter.is_production_enabled
 where patrol.id=p_patrol_id and patrol.user_id=v_uid and (patrol.status='CLAIMABLE' or (patrol.status='ONGOING' and patrol.expires_at<=now())) and patrol.has_battle_event and not coalesce(patrol.battle_resolved,false) for update of patrol;
 if not found then raise exception 'eligible patrol encounter not found' using errcode='P0002'; end if;
 update public.user_patrols set status='CLAIMABLE' where id=p_patrol_id and status='ONGOING';
 select array_remove(array[deck.character_1_id::text,deck.character_2_id::text,deck.character_3_id::text,deck.character_4_id::text,deck.character_5_id::text],null) into v_ids from public.pvp_defense_decks deck where deck.user_id=v_uid;
 if coalesce(cardinality(v_ids),0)=0 then select array[owned.id::text] into v_ids from public.user_characters owned where owned.user_id=v_uid and owned.character_id=v_patrol.character_id order by owned.created_at limit 1; end if;
 v_player:=public.build_server_battle_snapshot(v_uid,v_ids,'PLAYER'); v_enemy:=public.canonical_quest_enemy_snapshot(coalesce(v_patrol.course_id,v_patrol.quest_id));
 if coalesce(jsonb_array_length(v_enemy),0)<>v_patrol.expected_members then raise exception 'canonical quest encounter member count mismatch' using errcode='23514'; end if;
 v_seed:=floor(random()*2147483646)::bigint+1;
 insert into public.battle_replay_sessions(requester_user_id,battle_mode,source_reference_id,tactic_id,enemy_tactic_id,random_seed,player_snapshot,enemy_snapshot,resolution_authority)
 values(v_uid,'QUEST',p_patrol_id,p_tactic_id,v_patrol.enemy_tactic,v_seed,v_player,v_enemy,'PATROL_SERVER') returning id into v_replay;
 return jsonb_build_object('replay_session_id',v_replay,'player_snapshot',v_player,'enemy_snapshot',v_enemy,'enemy_tactic',v_patrol.enemy_tactic);
end $$;

revoke all on function public.canonical_quest_is_unlocked(uuid,text),public.get_canonical_quest_progression() from public,anon;
grant execute on function public.get_canonical_quest_progression() to authenticated;
grant execute on function public.canonical_quest_is_unlocked(uuid,text) to service_role;

do $$ declare encounter record; member jsonb; skill_id text; exclusive_count integer; begin
 if (select count(*) from public.canonical_quest_master where version='2026-08-22' and unlock_condition='OPEN')<>7 then raise exception 'Quest v2 EASY unlock count mismatch'; end if;
 if (select count(*) from public.canonical_quest_master where version='2026-08-22' and unlock_condition like 'FIRST_CLEAR:%')<>14 then raise exception 'Quest v2 prerequisite count mismatch'; end if;
 for encounter in select * from public.canonical_quest_encounter_master where version='2026-08-22' loop
  if jsonb_array_length(encounter.members)<>(case when encounter.difficulty='EASY' then 3 else 5 end) then raise exception 'Quest v2 member count mismatch: %',encounter.quest_id; end if;
  for member in select value from jsonb_array_elements(encounter.members) loop
   if jsonb_array_length(member->'equipmentLoadout')<>0 then raise exception 'Quest enemy equipment is not NONE'; end if;
   if jsonb_array_length(member->'skillLoadout')<1 or jsonb_array_length(member->'skillLoadout')>(case when encounter.difficulty='HARD' then 3 else 2 end) then raise exception 'Quest Skill progression mismatch: %',encounter.quest_id; end if;
   if jsonb_array_length(member->'skillLoadout')>public.canonical_skill_slot_count((member->>'awakening')::integer) then raise exception 'Quest Skill slot overflow'; end if;
   select count(*) into exclusive_count from jsonb_array_elements_text(member->'skillLoadout') loadout(skill_id) join public.canonical_skill_master skill on skill.version='2026-08-21' and skill.skill_id=loadout.skill_id where skill.exclusive_character_id is not null;
   if exclusive_count>1 or exists(select 1 from jsonb_array_elements_text(member->'skillLoadout') loadout(skill_id) left join public.canonical_skill_master skill on skill.version='2026-08-21' and skill.skill_id=loadout.skill_id where skill.skill_id is null or (skill.exclusive_character_id is not null and skill.exclusive_character_id<>member->>'characterId')) then raise exception 'Quest Skill ownership mismatch'; end if;
  end loop;
 end loop;
end $$;
commit;
notify pgrst,'reload schema';
`;

fs.writeFileSync(output, sql);
console.log(`Generated ${output}`);
