-- Generated by scripts/generate_pvp_raid_production_db_migration.mjs. Do not hand-edit canonical seed values.
begin;

create table if not exists public.canonical_pvp_production_master(version text primary key, payload jsonb not null, is_production_enabled boolean not null);
insert into public.canonical_pvp_production_master values('2026-08-22','{"pvp":{"version":"2026-08-22","status":"PRODUCTION_FROZEN","modes":{"PRACTICE":{"cost":0,"cashReward":0,"ratingImpact":false,"rankingImpact":false,"missionProgress":false},"OFFICIAL":{"cost":1,"winCash":500,"lossCash":250,"ratingImpact":true,"rankingImpact":true,"missionProgress":true}},"rating":{"initial":1000,"minimum":0,"maximum":null,"scale":400,"winK":32,"lossK":16},"season":{"period":"JST_CALENDAR_MONTH","softResetAnchor":1000,"softResetBp":5000},"opponentClass":{"strongerMinDifference":101,"equalMinDifference":-100,"equalMaxDifference":100,"weakerMaxDifference":-101}},"matchmaking":{"version":"2026-08-22","status":"PRODUCTION_FROZEN","candidateLimit":5,"tiers":[{"tier":1,"ratingRange":300,"powerMinBp":7000,"powerMaxBp":14000},{"tier":2,"ratingRange":500,"powerMinBp":5000,"powerMaxBp":18000},{"tier":3,"ratingRange":null,"powerMinBp":null,"powerMaxBp":null}],"selfExcluded":true,"validDefenseRequired":true,"botFallback":false,"sameOpponentRecurrence":true,"refreshAllowed":true},"ranking":{"version":"2026-08-22","status":"PRODUCTION_FROZEN","rankingTypes":["PVP","RAID_PERSONAL","RAID_GUILD"],"displayRank":"COMPETITION","scoreTieSharesRank":true,"stableOrder":["SCORE_DESC","ACHIEVED_AT_ASC","STABLE_ID_ASC"],"pagination":{"limit":true,"offset":true,"selfRank":true},"rewardDelivery":"SERVER_PRESENT_EXACTLY_ONCE"}}'::jsonb,true)
on conflict(version) do update set payload=excluded.payload,is_production_enabled=excluded.is_production_enabled;

create table if not exists public.canonical_pvp_ranking_rewards(version text not null,rank_min integer not null,rank_max integer not null,item_id text not null,quantity integer not null check(quantity>0),primary key(version,rank_min,rank_max,item_id));
insert into public.canonical_pvp_ranking_rewards values
('2026-08-22',1,1,'CASH',30000),
('2026-08-22',1,1,'NORMAL_GACHA_TICKET_CHARACTER',3),
('2026-08-22',2,3,'CASH',20000),
('2026-08-22',2,3,'NORMAL_GACHA_TICKET_CHARACTER',2),
('2026-08-22',4,10,'CASH',10000),
('2026-08-22',4,10,'NORMAL_GACHA_TICKET_CHARACTER',1),
('2026-08-22',11,50,'CASH',5000)
on conflict(version,rank_min,rank_max,item_id) do update set quantity=excluded.quantity;

create table if not exists public.pvp_ranking_reward_grants(season_id uuid not null references public.ranking_seasons(id),user_id uuid not null references public.users(id),rank_position integer not null,item_id text not null,quantity integer not null,granted_at timestamptz not null default now(),primary key(season_id,user_id,item_id));

create or replace function public.canonical_pvp_expected_score(p_player integer,p_opponent integer) returns numeric language sql immutable as $$ select 1::numeric/(1+power(10::numeric,(p_opponent-p_player)::numeric/400)) $$;
create or replace function public.canonical_pvp_rating_delta(p_player integer,p_opponent integer,p_result text) returns integer language plpgsql immutable as $$
declare v_expected numeric:=public.canonical_pvp_expected_score(p_player,p_opponent);
begin if p_result='WIN' then return round(32*(1-v_expected)); elsif p_result='LOSS' then return round(16*(0-v_expected)); end if; raise exception 'invalid PvP result' using errcode='22023'; end $$;
create or replace function public.canonical_pvp_soft_reset(p_rating integer) returns integer language sql immutable as $$ select greatest(0,1000+floor((p_rating-1000)*0.5)::integer) $$;

update public.pvp_match_rewards_master set diamond_reward=0,exp_reward=0,cash_reward=case result when 'VICTORY' then 500 when 'DEFEAT' then 250 else cash_reward end where result in('VICTORY','DEFEAT');

create or replace function public.get_pvp_opponents(p_user_id uuid,p_my_points integer) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_my_power bigint; v_result jsonb;
begin
 if auth.uid() is null or auth.uid()<>p_user_id then raise exception 'not authorized' using errcode='42501'; end if;
 select coalesce(total_power,0) into v_my_power from public.user_power_rankings where user_id=p_user_id;
 with candidates as (
  select player.id,player.username,coalesce(rank.rank_points,1000) rating,coalesce(power.total_power,0) total_power,coalesce(deck.tactic,'BALANCED') tactic,
   deck.character_1_id,deck.character_2_id,deck.character_3_id,deck.character_4_id,deck.character_5_id,
   case
    when abs(coalesce(rank.rank_points,1000)-coalesce(p_my_points,1000))<=300 and (coalesce(v_my_power,0)<=0 or coalesce(power.total_power,0)*10000 between v_my_power*7000 and v_my_power*14000) then 1
    when abs(coalesce(rank.rank_points,1000)-coalesce(p_my_points,1000))<=500 and (coalesce(v_my_power,0)<=0 or coalesce(power.total_power,0)*10000 between v_my_power*5000 and v_my_power*18000) then 2
    else 3 end match_tier
  from public.users player join public.pvp_defense_decks deck on deck.user_id=player.id
  left join public.pvp_ranks rank on rank.user_id=player.id left join public.user_power_rankings power on power.user_id=player.id
  where player.id<>p_user_id and deck.character_1_id is not null
 ), selected as (select * from candidates order by match_tier,abs(rating-coalesce(p_my_points,1000)),id limit 5)
 select coalesce(jsonb_agg(jsonb_build_object('opponent_user_id',id,'opponent_username',username,'opponent_points',rating,'opponent_power',total_power,'opponent_rank',(select count(distinct r.rank_points)+1 from public.pvp_ranks r where r.rank_points>selected.rating),'match_tier',match_tier,
  'rating_difference',rating-coalesce(p_my_points,1000),'opponent_class',case when rating-coalesce(p_my_points,1000)>=101 then 'STRONGER' when rating-coalesce(p_my_points,1000)<=-101 then 'WEAKER' else 'EQUAL' end,
  'win_rating_delta',public.canonical_pvp_rating_delta(coalesce(p_my_points,1000),rating,'WIN'),'loss_rating_delta',public.canonical_pvp_rating_delta(coalesce(p_my_points,1000),rating,'LOSS'),
  'tactic',tactic,'defense_character_ids',to_jsonb(array_remove(array[character_1_id,character_2_id,character_3_id,character_4_id,character_5_id]::text[],null)),
  'defense_characters',coalesce((select jsonb_agg(jsonb_build_object('slot',slot.slot_no,'character_master_id',release.character_id,'display_name',release.display_name,'rarity',release.rarity,'level',coalesce(owned.level,1),'asset_identifier',release.asset_path) order by slot.slot_no) from (values(1,character_1_id),(2,character_2_id),(3,character_3_id),(4,character_4_id),(5,character_5_id))slot(slot_no,owned_or_master_id) left join public.user_characters owned on owned.user_id=selected.id and owned.id::text=slot.owned_or_master_id join public.character_release_master release on release.character_id=coalesce(owned.character_id,slot.owned_or_master_id) and release.is_enabled where slot.owned_or_master_id is not null),'[]'::jsonb)) order by match_tier,abs(rating-coalesce(p_my_points,1000)),id),'[]'::jsonb) into v_result from selected;
 return v_result;
end $$;

create or replace function public.finalize_pvp_battle(p_replay_id uuid,p_result jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_replay public.battle_replay_sessions%rowtype; v_win boolean; v_player integer; v_opponent integer; v_delta integer; v_cash integer; v_new integer; v_final jsonb; v_name text;
begin
 select * into v_replay from public.battle_replay_sessions where id=p_replay_id for update;
 if not found then raise exception 'PvP replay not found' using errcode='P0002'; end if;
 if v_replay.battle_mode<>'PVP' or v_replay.resolution_authority<>'PVP_SERVER' then raise exception 'replay is not official PvP' using errcode='42501'; end if;
 if v_replay.finalization_status='FINALIZED' then return v_replay.finalization_result; end if;
 if v_replay.status<>'PENDING' or v_replay.finalization_status<>'PENDING' then raise exception 'PvP replay is not finalizable' using errcode='23514'; end if;
 perform public.validate_official_battle_result(p_result); v_win:=p_result->>'winner'='PLAYER';
 v_player:=coalesce((v_replay.official_context->>'playerRankPointsAtStart')::integer,1000); v_opponent:=coalesce((v_replay.official_context->>'opponentRankPointsAtStart')::integer,1000);
 v_delta:=public.canonical_pvp_rating_delta(v_player,v_opponent,case when v_win then 'WIN' else 'LOSS' end); v_cash:=case when v_win then 500 else 250 end;
 insert into public.pvp_ranks(user_id,rank_points,daily_wins,season_wins,updated_at) values(v_replay.requester_user_id,greatest(1000+v_delta,0),case when v_win then 1 else 0 end,case when v_win then 1 else 0 end,now())
 on conflict(user_id) do update set rank_points=greatest(public.pvp_ranks.rank_points+v_delta,0),daily_wins=public.pvp_ranks.daily_wins+case when v_win then 1 else 0 end,season_wins=public.pvp_ranks.season_wins+case when v_win then 1 else 0 end,updated_at=now() returning rank_points into v_new;
 update public.users set cash=cash+v_cash where id=v_replay.requester_user_id;
 select username into v_name from public.users where id=v_replay.requester_user_id;
 insert into public.pvp_defense_logs(user_id,attacker_id,attacker_name,result,points_change) values(v_replay.source_reference_id,v_replay.requester_user_id,v_name,case when v_win then 'DEFEAT' else 'VICTORY' end,-v_delta);
 v_final:=p_result||jsonb_build_object('mode','PVP','oldRating',v_player,'opponentRating',v_opponent,'rankDelta',v_delta,'newRankPoints',v_new,'remainingPvpPoints',coalesce((v_replay.official_context->>'remainingPvpPoints')::integer,0),'rewards',jsonb_build_object('cash',v_cash,'diamonds',0,'xp',0));
 insert into public.battle_replay_events(battle_replay_session_id,event_index,round_number,event_type,payload) select p_replay_id,greatest(coalesce((e.value->>'index')::integer,e.ordinality::integer-1),0),greatest(coalesce((e.value->>'round')::integer,1),1),coalesce(nullif(e.value->>'type',''),'UNKNOWN'),coalesce(e.value->'payload','{}'::jsonb) from jsonb_array_elements(p_result->'events') with ordinality e(value,ordinality) on conflict do nothing;
 update public.battle_replay_sessions set status='RESOLVED',result=v_final,resolved_at=now(),finalization_status='FINALIZED',finalized_at=now(),finalization_result=v_final where id=p_replay_id; return v_final;
end $$;

create or replace function public.get_pvp_rankings_page(p_limit integer default 50,p_offset integer default 0) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();
begin if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if; if p_limit not between 1 and 100 or p_offset not between 0 and 10000 then raise exception 'invalid pagination' using errcode='22023'; end if;
 return jsonb_build_object('rows',coalesce((with totals as(select rank.user_id,u.username,rank.rank_points score,rank.updated_at achieved_at,coalesce(power.total_power,0) total_power from public.pvp_ranks rank join public.users u on u.id=rank.user_id left join public.user_power_rankings power on power.user_id=rank.user_id),ranked as(select *,rank() over(order by score desc) rank_position from totals) select jsonb_agg(to_jsonb(page) order by score desc,achieved_at,user_id) from(select * from ranked order by score desc,achieved_at,user_id limit p_limit offset p_offset)page),'[]'::jsonb),'selfRank',(with totals as(select user_id,rank_points score,updated_at achieved_at from public.pvp_ranks),ranked as(select *,rank() over(order by score desc) rank_position from totals) select to_jsonb(ranked) from ranked where user_id=v_uid));
end $$;

create or replace function public.finalize_pvp_season_rewards(p_season_id uuid) returns integer language plpgsql security definer set search_path=public as $$
declare row record; reward record; granted integer:=0;
begin
 if not exists(select 1 from public.ranking_seasons where id=p_season_id and ranking_type='PVP' and ends_at<=clock_timestamp()) then raise exception 'PvP season is not finalizable' using errcode='23514'; end if;
 for row in with ranked as(select rank.user_id,rank.rank_points,rank() over(order by rank.rank_points desc) pos from public.pvp_ranks rank) select * from ranked where pos<=50 loop
  for reward in select * from public.canonical_pvp_ranking_rewards where version='2026-08-22' and row.pos between rank_min and rank_max loop
   insert into public.pvp_ranking_reward_grants(season_id,user_id,rank_position,item_id,quantity) values(p_season_id,row.user_id,row.pos,reward.item_id,reward.quantity) on conflict do nothing;
   if found then insert into public.presents(user_id,item_id,quantity,message,status,expire_at) values(row.user_id,reward.item_id,reward.quantity,'PvPシーズンランキング報酬','UNCLAIMED',now()+interval '30 days');granted:=granted+1; end if;
  end loop;
 end loop; return granted;
end $$;

create or replace function public.soft_reset_pvp_ratings() returns integer language plpgsql security definer set search_path=public as $$
declare affected integer; begin update public.pvp_ranks set rank_points=public.canonical_pvp_soft_reset(rank_points),daily_wins=0,season_wins=0,updated_at=now();get diagnostics affected=row_count;return affected;end $$;

create table if not exists public.canonical_raid_production_master(version text primary key,payload jsonb not null,is_production_enabled boolean not null);
insert into public.canonical_raid_production_master values('2026-08-22','{"raid":{"version":"2026-08-22","status":"PRODUCTION_FROZEN","activeTownCount":2,"durationHours":24,"rotationTimezone":"Asia/Tokyo","rotationHour":0,"referenceLevel":30,"referenceParticipants":20,"referenceBattlesPerParticipant":2,"bossHpBattleMultiplier":40,"raidTowns":[{"townId":"shinjuku","displayName":"新宿","profile":"HIGH_ATK"},{"townId":"shibuya","displayName":"渋谷","profile":"HIGH_DEF"},{"townId":"ikebukuro","displayName":"池袋","profile":"HIGH_SPD"},{"townId":"roppongi","displayName":"六本木","profile":"DEBUFF"},{"townId":"akihabara","displayName":"秋葉原","profile":"AOE"}],"profileMultipliersBp":{"HIGH_ATK":{"hp":10000,"atk":13500,"def":9000,"spd":10000,"luk":10000},"HIGH_DEF":{"hp":10000,"atk":9000,"def":14000,"spd":10000,"luk":10000},"HIGH_SPD":{"hp":10000,"atk":10000,"def":10000,"spd":13000,"luk":10000},"DEBUFF":{"hp":10000,"atk":10000,"def":10000,"spd":10000,"luk":10000},"AOE":{"hp":10000,"atk":10000,"def":10000,"spd":10000,"luk":10000}},"tuningStatus":"P0_TUNABLE"},"ranking":{"version":"2026-08-22","status":"PRODUCTION_FROZEN","rankingTypes":["PVP","RAID_PERSONAL","RAID_GUILD"],"displayRank":"COMPETITION","scoreTieSharesRank":true,"stableOrder":["SCORE_DESC","ACHIEVED_AT_ASC","STABLE_ID_ASC"],"pagination":{"limit":true,"offset":true,"selfRank":true},"rewardDelivery":"SERVER_PRESENT_EXACTLY_ONCE"}}'::jsonb,true) on conflict(version) do update set payload=excluded.payload,is_production_enabled=true;
create table if not exists public.canonical_raid_boss_master(boss_id text primary key,town_id text not null unique,display_name text not null,profile_type text not null,attribute text not null,reference_level integer not null,max_hp bigint not null,atk integer not null,def integer not null,spd integer not null,luk integer not null,skill_loadout jsonb not null,tuning_status text not null,is_production_enabled boolean not null);
insert into public.canonical_raid_boss_master values
('RAID_BOSS_001','shinjuku','新宿・剛腕頭領','HIGH_ATK','EVIL',30,22500000,8714,5166,358,28,'[{"id":"BASIC_ATTACK","name":"通常攻撃","target":"ENEMY_SINGLE","cooldown":0,"availableFromRound":1,"effects":["DAMAGE 80% ATK"]},{"id":"RAID_SKILL_HIGH_ATK","name":"強襲","activationType":"ACTIVE","target":"ENEMY_SINGLE","cooldown":3,"availableFromRound":1,"effects":["DAMAGE 180% ATK"]}]'::jsonb,'P0_TUNABLE',true),
('RAID_BOSS_002','shibuya','渋谷・鉄壁頭領','HIGH_DEF','ORDER',30,31900000,5809,8036,358,28,'[{"id":"BASIC_ATTACK","name":"通常攻撃","target":"ENEMY_SINGLE","cooldown":0,"availableFromRound":1,"effects":["DAMAGE 80% ATK"]},{"id":"RAID_SKILL_HIGH_DEF","name":"鉄壁","activationType":"ACTIVE","target":"SELF","cooldown":3,"availableFromRound":1,"effects":["DEF +30% / 2T"]}]'::jsonb,'P0_TUNABLE',true),
('RAID_BOSS_003','ikebukuro','池袋・疾風頭領','HIGH_SPD','CHAOS',30,27600000,6455,5740,465,28,'[{"id":"BASIC_ATTACK","name":"通常攻撃","target":"ENEMY_SINGLE","cooldown":0,"availableFromRound":1,"effects":["DAMAGE 80% ATK"]},{"id":"RAID_SKILL_HIGH_SPD","name":"迅撃","activationType":"ACTIVE","target":"ENEMY_SINGLE","cooldown":3,"availableFromRound":1,"effects":["DAMAGE 145% ATK"]}]'::jsonb,'P0_TUNABLE',true),
('RAID_BOSS_004','roppongi','六本木・幻惑頭領','DEBUFF','JUSTICE',30,22200000,6455,5740,358,28,'[{"id":"BASIC_ATTACK","name":"通常攻撃","target":"ENEMY_SINGLE","cooldown":0,"availableFromRound":1,"effects":["DAMAGE 80% ATK"]},{"id":"RAID_SKILL_DEBUFF","name":"威圧","activationType":"ACTIVE","target":"ENEMY_ALL","cooldown":4,"availableFromRound":2,"effects":["DAMAGE 110% ATK","ATK -20% / 2T"]}]'::jsonb,'P0_TUNABLE',true),
('RAID_BOSS_005','akihabara','秋葉原・殲滅頭領','AOE','EVIL',30,25600000,6455,5740,358,28,'[{"id":"BASIC_ATTACK","name":"通常攻撃","target":"ENEMY_SINGLE","cooldown":0,"availableFromRound":1,"effects":["DAMAGE 80% ATK"]},{"id":"RAID_SKILL_AOE","name":"一斉制圧","activationType":"ACTIVE","target":"ENEMY_ALL","cooldown":4,"availableFromRound":2,"effects":["DAMAGE 135% ATK"]}]'::jsonb,'P0_TUNABLE',true)
on conflict(boss_id) do update set town_id=excluded.town_id,display_name=excluded.display_name,profile_type=excluded.profile_type,attribute=excluded.attribute,reference_level=excluded.reference_level,max_hp=excluded.max_hp,atk=excluded.atk,def=excluded.def,spd=excluded.spd,luk=excluded.luk,skill_loadout=excluded.skill_loadout,tuning_status=excluded.tuning_status,is_production_enabled=true;

alter table public.raid_boss_master add column if not exists profile_type text,add column if not exists attribute text,add column if not exists town_id text;
insert into public.raid_boss_master(id,name,base_hp,base_atk,base_def,spd,duration_minutes,rewards,boss_name,level,max_hp,atk,def,luk,skills,enabled,profile_type,attribute,town_id)
select boss_id,display_name,max_hp,atk,def,spd,1440,'[]'::jsonb,display_name,reference_level,max_hp,atk,def,luk,skill_loadout,true,profile_type,attribute,town_id from public.canonical_raid_boss_master
on conflict(id) do update set name=excluded.name,base_hp=excluded.base_hp,base_atk=excluded.base_atk,base_def=excluded.base_def,spd=excluded.spd,boss_name=excluded.boss_name,level=excluded.level,max_hp=excluded.max_hp,atk=excluded.atk,def=excluded.def,luk=excluded.luk,skills=excluded.skills,enabled=true,profile_type=excluded.profile_type,attribute=excluded.attribute,town_id=excluded.town_id;
update public.raid_boss_master set enabled=false where id='BOSS_001';

create table if not exists public.canonical_raid_reward_master(version text not null,reward_type text not null,reward_key text not null,finalized_battles integer,raid_points_consumed integer,rank_min integer,rank_max integer,item_id text not null,quantity integer not null,primary key(version,reward_type,reward_key,item_id));
insert into public.canonical_raid_reward_master values
('2026-08-22','PROGRESS','PARTICIPATION_1',1,null,null,null,'CASH',300),
('2026-08-22','PROGRESS','ACTIVE_3',3,null,null,null,'CHAR_EXP_M',1),
('2026-08-22','PROGRESS','FULL_POINTS_5',null,5,null,null,'EQUIP_EXP_M',1),
('2026-08-22','CLEAR','CLEAR',null,null,null,null,'CASH',1000),
('2026-08-22','CLEAR','CLEAR',null,null,null,null,'EQUIP_LB_PART',1),
('2026-08-22','PERSONAL_RANK','RANK_1_1',null,null,1,1,'CASH',5000),
('2026-08-22','PERSONAL_RANK','RANK_1_1',null,null,1,1,'NORMAL_GACHA_TICKET_CHARACTER',1),
('2026-08-22','PERSONAL_RANK','RANK_2_3',null,null,2,3,'CASH',3000),
('2026-08-22','PERSONAL_RANK','RANK_4_10',null,null,4,10,'CASH',1500),
('2026-08-22','GUILD_RANK','RANK_1_1',null,null,1,1,'CASH',3000),
('2026-08-22','GUILD_RANK','RANK_2_3',null,null,2,3,'CASH',2000),
('2026-08-22','GUILD_RANK','RANK_4_10',null,null,4,10,'CASH',1000)
on conflict(version,reward_type,reward_key,item_id) do update set finalized_battles=excluded.finalized_battles,raid_points_consumed=excluded.raid_points_consumed,rank_min=excluded.rank_min,rank_max=excluded.rank_max,quantity=excluded.quantity;

create table if not exists public.raid_production_reward_grants(raid_boss_instance_id uuid not null references public.raid_bosses(id),user_id uuid not null references public.users(id),reward_type text not null,reward_key text not null,item_id text not null,quantity integer not null,granted_at timestamptz not null default now(),primary key(raid_boss_instance_id,user_id,reward_type,reward_key,item_id));
create table if not exists public.raid_instance_user_progress(raid_boss_instance_id uuid not null references public.raid_bosses(id),user_id uuid not null references public.users(id),finalized_battles integer not null default 0,raid_points_consumed integer not null default 0,last_guild_id uuid,updated_at timestamptz not null default now(),primary key(raid_boss_instance_id,user_id));
alter table public.raid_bosses add column if not exists rotation_date date;

create or replace function public.canonical_raid_rotation_pair(p_date date) returns text[] language sql immutable as $$
 with towns as (select array['shinjuku','shibuya','ikebukuro','roppongi','akihabara']::text[] value),pairs as (select array[value[i],value[j]] pair,row_number() over(order by i,j)-1 idx from towns,generate_subscripts(value,1)i,generate_subscripts(value,1)j where i<j)
 select pair from pairs where idx=mod((p_date-date '2026-08-22')::integer,10)
$$;

create or replace function public.grant_canonical_raid_reward(p_instance uuid,p_user uuid,p_type text,p_key text) returns integer language plpgsql security definer set search_path=public as $$
declare row record; granted integer:=0;
begin for row in select * from public.canonical_raid_reward_master where version='2026-08-22' and reward_type=p_type and reward_key=p_key loop
 insert into public.raid_production_reward_grants values(p_instance,p_user,p_type,p_key,row.item_id,row.quantity,now()) on conflict do nothing;
 if found then insert into public.presents(user_id,item_id,quantity,message,status,expire_at) values(p_user,row.item_id,row.quantity,'レイド報酬','UNCLAIMED',now()+interval '30 days'); granted:=granted+1; end if;
 end loop; return granted; end $$;

create or replace function public.rotate_daily_raids() returns void language plpgsql security definer set search_path=public as $$
declare v_today date:=(clock_timestamp() at time zone 'Asia/Tokyo')::date; v_pair text[]; v_town text; v_master record; v_start timestamptz; v_end timestamptz;
begin
 perform pg_advisory_xact_lock(hashtextextended('CANONICAL_RAID_ROTATION',0));
 for v_master in select id from public.raid_bosses where status='ACTIVE' and expires_at<=clock_timestamp() for update loop perform public.finalize_expired_raid_instance(v_master.id); end loop;
 if exists(select 1 from public.raid_bosses where status='ACTIVE' and expires_at>clock_timestamp()) then return; end if;
 v_pair:=public.canonical_raid_rotation_pair(v_today); v_start:=(v_today::timestamp at time zone 'Asia/Tokyo'); v_end:=v_start+interval '24 hours';
 foreach v_town in array v_pair loop
  select * into v_master from public.canonical_raid_boss_master where town_id=v_town and is_production_enabled;
  insert into public.raid_bosses(boss_id,boss_master_id,current_hp,max_hp,base_id,status,spawned_at,expires_at,cycle_id,rotation_date) values(v_master.boss_id,v_master.boss_id,v_master.max_hp,v_master.max_hp,v_town,'ACTIVE',v_start,v_end,gen_random_uuid(),v_today);
 end loop;
end $$;

create or replace function public.get_active_raids() returns jsonb language plpgsql security definer set search_path=public as $$
begin if auth.uid() is null then raise exception 'authentication required' using errcode='42501'; end if; perform public.rotate_daily_raids();
 return coalesce((select jsonb_agg(jsonb_build_object('id',boss.id,'bossMasterId',master.boss_id,'bossName',master.display_name,'profileType',master.profile_type,'attribute',master.attribute,'level',master.reference_level,'currentHp',boss.current_hp,'maxHp',boss.max_hp,'baseId',boss.base_id,'spawnedAt',boss.spawned_at,'expiresAt',boss.expires_at,'status',boss.status,'skillLoadout',master.skill_loadout) order by boss.base_id) from public.raid_bosses boss join public.canonical_raid_boss_master master on master.boss_id=boss.boss_master_id where boss.status='ACTIVE' and boss.expires_at>clock_timestamp()),'[]'::jsonb);
end $$;

create or replace function public.start_raid_battle(p_instance_id uuid,p_character_ids text[],p_tactic text default 'ATTACK_PRIORITY') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_user public.users%rowtype; v_instance record; v_cost integer; v_cost_type text; v_guild uuid; v_players jsonb; v_enemy jsonb; v_replay uuid; v_seed bigint;
begin
 if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if;
 if p_tactic not in('ATTACK_PRIORITY','HEAL_PRIORITY','SKILL_PRIORITY','BALANCED','WEAKNESS_FOCUS') then raise exception 'invalid tactic' using errcode='22023'; end if;
 perform public.sync_and_recover_vitality_and_pvp_points(v_uid); select * into v_user from public.users where id=v_uid for update;
 if v_user.level<5 then raise exception 'player level 5 is required' using errcode='23514'; end if;
 select boss.*,master.display_name,master.attribute,master.reference_level,master.atk,master.def,master.spd,master.luk,master.skill_loadout,master.profile_type into v_instance from public.raid_bosses boss join public.canonical_raid_boss_master master on master.boss_id=boss.boss_master_id where boss.id=p_instance_id and boss.status='ACTIVE' and boss.expires_at>clock_timestamp() for update of boss;
 if not found then raise exception 'Raid instance is not active' using errcode='P0002'; end if;
 if not v_user.raid_free_entry_consumed then v_cost:=0;v_cost_type:='FREE_FIRST';update public.users set raid_free_entry_consumed=true where id=v_uid;
 elsif v_user.raid_points>=1 then v_cost:=1;v_cost_type:='RAID_POINT';update public.users set raid_points=raid_points-1,raid_points_last_recovered_at=case when raid_points=5 then now() else raid_points_last_recovered_at end where id=v_uid;v_user.raid_points:=v_user.raid_points-1;
 else raise exception 'insufficient Raid points' using errcode='23514'; end if;
 select guild_id into v_guild from public.guild_members where user_id=v_uid;
 v_players:=public.build_server_battle_snapshot(v_uid,p_character_ids,'PLAYER');
 v_enemy:=jsonb_build_array(jsonb_build_object('id','raid_'||v_instance.id,'characterId',v_instance.boss_master_id,'name',v_instance.display_name,'team','ENEMY','alignment',v_instance.attribute,'level',v_instance.reference_level,'profileType',v_instance.profile_type,'stats',jsonb_build_object('hp',v_instance.max_hp,'atk',v_instance.atk,'def',v_instance.def,'spd',v_instance.spd,'luk',v_instance.luk),'skills',v_instance.skill_loadout));
 v_seed:=floor(random()*2147483646)::bigint+1;
 insert into public.battle_replay_sessions(requester_user_id,battle_mode,source_reference_id,tactic_id,random_seed,player_snapshot,enemy_snapshot,resolution_authority,finalization_status,official_context) values(v_uid,'RAID',p_instance_id,p_tactic,v_seed,v_players,v_enemy,'RAID_SERVER','PENDING',jsonb_build_object('guildIdSnapshot',v_guild,'costType',v_cost_type,'cost',v_cost,'remainingRaidPoints',v_user.raid_points,'bossHpAtStart',v_instance.current_hp,'bossMaxHp',v_instance.max_hp,'baseId',v_instance.base_id,'bossProfile',v_instance.profile_type)) returning id into v_replay;
 return jsonb_build_object('replay_session_id',v_replay,'player_snapshot',v_players,'enemy_snapshot',v_enemy,'cost_type',v_cost_type,'cost',v_cost,'remaining_raid_points',v_user.raid_points,'guild_id_snapshot',v_guild);
end $$;

create or replace function public.finalize_raid_battle(p_replay_id uuid,p_result jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_replay public.battle_replay_sessions%rowtype; v_instance public.raid_bosses%rowtype; v_raw bigint; v_applied bigint; v_remaining bigint; v_total bigint; v_progress record; v_final jsonb;
begin
 select * into v_replay from public.battle_replay_sessions where id=p_replay_id for update;
 if not found or v_replay.battle_mode<>'RAID' or v_replay.resolution_authority<>'RAID_SERVER' then raise exception 'not an official Raid replay' using errcode='42501'; end if;
 if v_replay.finalization_status='FINALIZED' then return v_replay.finalization_result; end if;
 if v_replay.status<>'PENDING' or v_replay.finalization_status<>'PENDING' then raise exception 'Raid replay is not finalizable' using errcode='23514'; end if;
 perform public.validate_official_battle_result(p_result); select * into v_instance from public.raid_bosses where id=v_replay.source_reference_id for update; if not found then raise exception 'Raid instance missing'; end if;
 v_raw:=greatest(coalesce((p_result->>'playerRawDamage')::bigint,0),0);v_applied:=least(v_raw,greatest(v_instance.current_hp,0));v_remaining:=greatest(v_instance.current_hp-v_applied,0);
 update public.raid_bosses set current_hp=v_remaining,status=case when v_remaining=0 then 'DEFEATED' else status end where id=v_instance.id;
 insert into public.raid_damage_logs(boss_id,raid_boss_id,user_id,damage,damage_dealt,raid_boss_instance_id,battle_replay_session_id,guild_id,raw_damage,applied_damage) values(v_instance.boss_id,v_instance.boss_id,v_replay.requester_user_id,v_raw,v_raw,v_instance.id,p_replay_id,nullif(v_replay.official_context->>'guildIdSnapshot','')::uuid,v_raw,v_applied);
 insert into public.raid_instance_user_progress(raid_boss_instance_id,user_id,finalized_battles,raid_points_consumed,last_guild_id) values(v_instance.id,v_replay.requester_user_id,1,case when v_replay.official_context->>'costType'='RAID_POINT' then 1 else 0 end,nullif(v_replay.official_context->>'guildIdSnapshot','')::uuid)
 on conflict(raid_boss_instance_id,user_id) do update set finalized_battles=public.raid_instance_user_progress.finalized_battles+1,raid_points_consumed=public.raid_instance_user_progress.raid_points_consumed+excluded.raid_points_consumed,last_guild_id=excluded.last_guild_id,updated_at=now() returning * into v_progress;
 for v_final in select jsonb_build_object('reward_key',r.reward_key) from public.canonical_raid_reward_master r where version='2026-08-22' and reward_type='PROGRESS' and (r.finalized_battles is null or r.finalized_battles<=v_progress.finalized_battles) and (r.raid_points_consumed is null or r.raid_points_consumed<=v_progress.raid_points_consumed) group by r.reward_key loop perform public.grant_canonical_raid_reward(v_instance.id,v_replay.requester_user_id,'PROGRESS',v_final->>'reward_key'); end loop;
 select coalesce(sum(raw_damage),0) into v_total from public.raid_damage_logs where raid_boss_instance_id=v_instance.id and user_id=v_replay.requester_user_id;
 v_final:=p_result||jsonb_build_object('mode','RAID','raidInstanceId',v_instance.id,'baseId',v_instance.base_id,'rawDamage',v_raw,'appliedDamage',v_applied,'remainingBossHp',v_remaining,'personalContribution',v_total,'guildIdSnapshot',v_replay.official_context->>'guildIdSnapshot','participationProgress',to_jsonb(v_progress));
 insert into public.battle_replay_events(battle_replay_session_id,event_index,round_number,event_type,payload) select p_replay_id,greatest(coalesce((e.value->>'index')::integer,e.ordinality::integer-1),0),greatest(coalesce((e.value->>'round')::integer,1),1),coalesce(nullif(e.value->>'type',''),'UNKNOWN'),coalesce(e.value->'payload','{}'::jsonb) from jsonb_array_elements(p_result->'events') with ordinality e(value,ordinality) on conflict do nothing;
 update public.battle_replay_sessions set status='RESOLVED',result=v_final,resolved_at=now(),finalization_status='FINALIZED',finalized_at=now(),finalization_result=v_final where id=p_replay_id;
 if v_remaining=0 then perform public.finalize_expired_raid_instance(v_instance.id); end if; return v_final;
end $$;

create or replace function public.finalize_expired_raid_instance(p_instance_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_instance public.raid_bosses%rowtype; row record;
begin
 select * into v_instance from public.raid_bosses where id=p_instance_id for update; if not found or v_instance.outcome_finalized_at is not null then return; end if;
 if v_instance.status='ACTIVE' and v_instance.expires_at>clock_timestamp() then return; end if;
 update public.raid_bosses set status=case when current_hp=0 then 'DEFEATED' else 'EXPIRED' end,outcome=case when current_hp=0 then 'DEFEAT_SUCCESS' else 'TIMEOUT_FAILURE' end,outcome_finalized_at=now() where id=p_instance_id;
 if v_instance.current_hp=0 then for row in select distinct user_id from public.raid_damage_logs where raid_boss_instance_id=p_instance_id loop perform public.grant_canonical_raid_reward(p_instance_id,row.user_id,'CLEAR','CLEAR'); end loop; end if;
 for row in with totals as(select user_id,sum(raw_damage)::bigint score,min(created_at) achieved_at from public.raid_damage_logs where raid_boss_instance_id=p_instance_id group by user_id),ranked as(select *,rank() over(order by score desc) pos from totals) select * from ranked where pos<=10 loop
  perform public.grant_canonical_raid_reward(p_instance_id,row.user_id,'PERSONAL_RANK',case when row.pos=1 then 'RANK_1_1' when row.pos<=3 then 'RANK_2_3' else 'RANK_4_10' end);
 end loop;
 for row in with totals as(select guild_id,sum(raw_damage)::bigint score,min(created_at) achieved_at from public.raid_damage_logs where raid_boss_instance_id=p_instance_id and guild_id is not null group by guild_id),ranked as(select *,rank() over(order by score desc) pos from totals) select ranked.*,member.user_id from ranked join public.guild_members member on member.guild_id=ranked.guild_id where pos<=10 and exists(select 1 from public.raid_damage_logs log where log.raid_boss_instance_id=p_instance_id and log.guild_id=ranked.guild_id and log.user_id=member.user_id) loop
  perform public.grant_canonical_raid_reward(p_instance_id,row.user_id,'GUILD_RANK',case when row.pos=1 then 'RANK_1_1' when row.pos<=3 then 'RANK_2_3' else 'RANK_4_10' end);
 end loop;
end $$;

create or replace function public.get_raid_rankings(p_instance_id uuid,p_limit integer default 100,p_offset integer default 0) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();
begin if v_uid is null then raise exception 'authentication required' using errcode='42501'; end if; if p_limit not between 1 and 100 or p_offset not between 0 and 10000 then raise exception 'invalid pagination' using errcode='22023'; end if;
 return jsonb_build_object(
 'individual',coalesce((with totals as(select log.user_id,u.username,sum(log.raw_damage)::bigint contribution,min(log.created_at) achieved_at from public.raid_damage_logs log join public.users u on u.id=log.user_id where log.raid_boss_instance_id=p_instance_id group by log.user_id,u.username),ranked as(select *,rank() over(order by contribution desc) rank_position from totals) select jsonb_agg(to_jsonb(page) order by contribution desc,achieved_at,user_id) from(select * from ranked order by contribution desc,achieved_at,user_id limit p_limit offset p_offset)page),'[]'::jsonb),
 'guild',coalesce((with totals as(select log.guild_id,g.name guild_name,sum(log.raw_damage)::bigint contribution,min(log.created_at) achieved_at,count(distinct log.user_id)::integer participant_count from public.raid_damage_logs log join public.guilds g on g.id=log.guild_id where log.raid_boss_instance_id=p_instance_id and log.guild_id is not null group by log.guild_id,g.name),ranked as(select *,rank() over(order by contribution desc) rank_position from totals) select jsonb_agg(to_jsonb(page) order by contribution desc,achieved_at,guild_id) from(select * from ranked order by contribution desc,achieved_at,guild_id limit p_limit offset p_offset)page),'[]'::jsonb),
 'selfRank',(with totals as(select user_id,sum(raw_damage)::bigint contribution,min(created_at) achieved_at from public.raid_damage_logs where raid_boss_instance_id=p_instance_id group by user_id),ranked as(select *,rank() over(order by contribution desc) rank_position from totals) select to_jsonb(ranked) from ranked where user_id=v_uid));
end $$;
create or replace function public.get_raid_rankings(p_instance_id uuid) returns jsonb language sql stable security definer set search_path=public as $$ select public.get_raid_rankings(p_instance_id,100,0) $$;

alter table public.canonical_pvp_production_master enable row level security; alter table public.canonical_pvp_ranking_rewards enable row level security; alter table public.canonical_raid_production_master enable row level security; alter table public.canonical_raid_boss_master enable row level security; alter table public.canonical_raid_reward_master enable row level security;
revoke all on public.canonical_pvp_production_master,public.canonical_pvp_ranking_rewards,public.canonical_raid_production_master,public.canonical_raid_boss_master,public.canonical_raid_reward_master from public,anon; grant select on public.canonical_pvp_production_master,public.canonical_pvp_ranking_rewards,public.canonical_raid_production_master,public.canonical_raid_boss_master,public.canonical_raid_reward_master to authenticated;
revoke all on function public.finalize_pvp_battle(uuid,jsonb),public.finalize_pvp_season_rewards(uuid),public.soft_reset_pvp_ratings(),public.finalize_raid_battle(uuid,jsonb),public.finalize_expired_raid_instance(uuid),public.rotate_daily_raids(),public.grant_canonical_raid_reward(uuid,uuid,text,text) from public,anon,authenticated; grant execute on function public.finalize_pvp_battle(uuid,jsonb),public.finalize_pvp_season_rewards(uuid),public.soft_reset_pvp_ratings(),public.finalize_raid_battle(uuid,jsonb),public.finalize_expired_raid_instance(uuid),public.rotate_daily_raids(),public.grant_canonical_raid_reward(uuid,uuid,text,text) to service_role;
revoke all on function public.get_pvp_opponents(uuid,integer),public.get_pvp_rankings_page(integer,integer),public.get_active_raids(),public.start_raid_battle(uuid,text[],text),public.get_raid_rankings(uuid),public.get_raid_rankings(uuid,integer,integer) from public,anon; grant execute on function public.get_pvp_opponents(uuid,integer),public.get_pvp_rankings_page(integer,integer),public.get_active_raids(),public.start_raid_battle(uuid,text[],text),public.get_raid_rankings(uuid),public.get_raid_rankings(uuid,integer,integer) to authenticated;
commit;
notify pgrst,'reload schema';
