-- Generated by scripts/generate_character_awakening_copy_equivalent_migration.mjs.
-- 00174 is physically applied in Development and intentionally remains immutable.
begin;

alter table public.user_characters add column if not exists awakening_progress integer not null default 0;
do $$ begin
  if not exists(select 1 from pg_constraint where conname='user_characters_awakening_progress_range') then
    alter table public.user_characters add constraint user_characters_awakening_progress_range check(awakening_progress between 0 and 3);
  end if;
end $$;

create or replace function public.canonical_character_awakening_required(p_awakening_level integer)
returns integer language sql immutable parallel safe as $$
  select case greatest(0,least(5,coalesce(p_awakening_level,0)))
    when 0 then 1 when 1 then 1 when 2 then 2 when 3 then 3 when 4 then 4 else 0 end
$$;

create or replace function public.apply_character_awakening_equivalent(
  p_user_id uuid, p_character_id uuid, p_equivalents integer default 1
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_level integer;
  v_progress integer;
  v_remaining integer:=greatest(0,coalesce(p_equivalents,0));
  v_required integer;
  v_advanced integer:=0;
begin
  select coalesce(awakening_level,0),coalesce(awakening_progress,0) into v_level,v_progress
  from public.user_characters where id=p_character_id and user_id=p_user_id for update;
  if not found then raise exception 'owned character not found' using errcode='P0002'; end if;
  if v_level>=5 then
    return jsonb_build_object('outcome','max','awakening_level',5,'awakening_progress',0,'awakening_required',0,'levels_advanced',0);
  end if;
  while v_remaining>0 and v_level<5 loop
    v_progress:=v_progress+1;
    v_remaining:=v_remaining-1;
    v_required:=public.canonical_character_awakening_required(v_level);
    if v_progress>=v_required then
      v_progress:=v_progress-v_required;
      v_level:=v_level+1;
      v_advanced:=v_advanced+1;
      if v_level>=5 then v_progress:=0; end if;
    end if;
  end loop;
  update public.user_characters set awakening_level=v_level,awakening_progress=v_progress where id=p_character_id and user_id=p_user_id;
  return jsonb_build_object(
    'outcome',case when v_advanced>0 then 'awakening' else 'awakening_progress' end,
    'awakening_level',v_level,'awakening_progress',v_progress,
    'awakening_required',public.canonical_character_awakening_required(v_level),
    'levels_advanced',v_advanced,'copy_equivalent_added',p_equivalents);
end $$;
revoke all on function public.apply_character_awakening_equivalent(uuid,uuid,integer) from public,anon,authenticated;

create or replace function public.awaken_character(p_character_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_user_id uuid:=auth.uid();
  v_level integer;
  v_result jsonb;
begin
  if v_user_id is null then raise exception 'authentication required' using errcode='42501'; end if;
  select coalesce(awakening_level,0) into v_level from public.user_characters where id=p_character_id and user_id=v_user_id for update;
  if not found then raise exception 'owned character not found' using errcode='P0002'; end if;
  if v_level>=5 then raise exception 'character awakening is already at maximum' using errcode='23514'; end if;
  update public.user_items set quantity=quantity-1,updated_at=now()
  where user_id=v_user_id and item_id='AWAKENING_BOOK' and quantity>=1;
  if not found then raise exception 'insufficient Awakening Book' using errcode='23514'; end if;
  v_result:=public.apply_character_awakening_equivalent(v_user_id,p_character_id,1);
  return jsonb_build_object('status','success','consumed_item_id','AWAKENING_BOOK','consumed_quantity',1)||v_result;
end $$;

create or replace function public.execute_character_gacha(
  p_user_id uuid,
  p_gacha_id text,
  p_pull_count integer,
  p_currency_type text,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_gacha record;
  v_user record;
  v_existing record;
  v_history record;
  v_result jsonb := '[]'::jsonb;
  v_response jsonb;
  v_item_id text;
  v_rarity text;
  v_ticket_item_id text;
  v_cost integer := 0;
  v_pity_before integer := 0;
  v_pity_after integer := 0;
  v_today date := (now() at time zone 'Asia/Tokyo')::date;
  v_index integer;
  v_inserted integer;
  v_is_special boolean;
  v_progress jsonb;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'not authorized';
  end if;
  if p_request_id is null then raise exception 'request_id is required'; end if;
  if p_pull_count is null or p_pull_count < 1 or p_pull_count > 10 then
    raise exception 'invalid pull count';
  end if;

  select id, gacha_type, cost_cash, cost_diamond into v_gacha
  from public.gacha_masters
  where id = p_gacha_id and gacha_type = 'CHARACTER';
  if not found then raise exception 'character gacha not found'; end if;

  v_is_special := p_gacha_id = 'CHAR_SPECIAL';
  if p_gacha_id not in ('CHAR_NORMAL', 'CHAR_SPECIAL') then
    raise exception 'unsupported character gacha';
  end if;
  if v_is_special and not exists (
    select 1 from public.feature_operating_states
    where feature_key = 'SPECIAL_GACHA' and state = 'OPEN'
  ) then
    raise exception 'special gacha is closed';
  end if;
  if p_currency_type = 'free' and (p_gacha_id <> 'CHAR_NORMAL' or p_pull_count <> 10) then
    raise exception 'daily free is only available as a normal ten-pull';
  end if;
  if p_currency_type not in ('free', 'cash', 'diamonds', 'ticket') then
    raise exception 'invalid currency type';
  end if;

  v_ticket_item_id := case when v_is_special then 'SPECIAL_TICKET_CHARACTER' else 'NORMAL_GACHA_TICKET_CHARACTER' end;
  v_cost := case p_currency_type
    when 'cash' then v_gacha.cost_cash * p_pull_count
    when 'diamonds' then v_gacha.cost_diamond * p_pull_count
    when 'ticket' then p_pull_count
    else 0 end;
  select coalesce(current_points, 0) into v_pity_before
  from public.user_gacha_pity_points
  where user_id = p_user_id and pity_master_id = 'pity_special_common';
  v_pity_before := coalesce(v_pity_before, 0);

  insert into public.gacha_execution_history (
    user_id, request_id, gacha_id, payment_source, pull_count,
    ticket_item_id, cost_amount, pity_before, pity_after
  ) values (
    p_user_id, p_request_id, p_gacha_id, p_currency_type, p_pull_count,
    case when p_currency_type = 'ticket' then v_ticket_item_id end,
    v_cost, v_pity_before, v_pity_before
  ) on conflict (user_id, request_id) do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted = 0 then
    select * into v_history from public.gacha_execution_history
    where user_id = p_user_id and request_id = p_request_id for update;
    if v_history.gacha_id <> p_gacha_id
       or v_history.payment_source <> p_currency_type
       or v_history.pull_count <> p_pull_count then
      raise exception 'request_id was already used for a different gacha request';
    end if;
    if v_history.status = 'COMPLETED' and v_history.result_payload is not null then
      return v_history.result_payload;
    end if;
    raise exception 'gacha request is already in progress';
  end if;

  if p_currency_type = 'free' then
    insert into public.user_daily_gacha_claims (user_id, gacha_type, last_claimed_date)
    values (p_user_id, 'CHARACTER', v_today)
    on conflict (user_id, gacha_type) do update
      set last_claimed_date = excluded.last_claimed_date, updated_at = now()
      where public.user_daily_gacha_claims.last_claimed_date < v_today;
    if not found then raise exception 'daily free gacha already claimed'; end if;
  elsif p_currency_type = 'cash' then
    update public.users set cash = cash - v_cost where id = p_user_id and cash >= v_cost;
    if not found then raise exception 'insufficient gacha currency'; end if;
  elsif p_currency_type = 'diamonds' then
    update public.users set neon_diamonds = neon_diamonds - v_cost
    where id = p_user_id and neon_diamonds >= v_cost;
    if not found then raise exception 'insufficient gacha currency'; end if;
  else
    update public.user_items set quantity = quantity - v_cost, updated_at = now()
    where user_id = p_user_id and item_id = v_ticket_item_id and quantity >= v_cost;
    if not found then raise exception 'insufficient gacha tickets'; end if;
  end if;

  for v_index in 1..p_pull_count loop
    v_rarity := public.draw_gacha_rarity(p_gacha_id);
    v_item_id := public.draw_gacha_item(p_gacha_id, v_rarity);
    if v_rarity is null or v_item_id is null then raise exception 'gacha bucket is empty'; end if;

    select id, awakening_level into v_existing
    from public.user_characters
    where user_id = p_user_id and character_id = v_item_id
    for update;

    if found and coalesce(v_existing.awakening_level, 0) < 5 then
      v_progress := public.apply_character_awakening_equivalent(p_user_id, v_existing.id, 1);
      v_result := v_result || jsonb_build_array(jsonb_build_object(
        'type', 'CHARACTER', 'character_id', v_item_id, 'rarity', v_rarity,
        'outcome', v_progress->>'outcome',
        'awakening_progress_added', 1,
        'awakening_level', (v_progress->>'awakening_level')::integer,
        'awakening_progress', (v_progress->>'awakening_progress')::integer,
        'awakening_required', (v_progress->>'awakening_required')::integer));
    elsif found then
      insert into public.user_items (user_id, item_id, quantity)
      values (p_user_id, 'AWAKENING_BOOK', 1)
      on conflict (user_id, item_id) do update
        set quantity = public.user_items.quantity + 1, updated_at = now();
      v_result := v_result || jsonb_build_array(jsonb_build_object(
        'type', 'CHARACTER', 'character_id', v_item_id, 'rarity', v_rarity, 'outcome', 'converted', 'converted_item_id', 'AWAKENING_BOOK', 'converted_quantity', 1));
    else
      insert into public.user_characters (user_id, character_id, level, awakening_level)
      values (p_user_id, v_item_id, 1, 0);
      v_result := v_result || jsonb_build_array(jsonb_build_object(
        'type', 'CHARACTER', 'character_id', v_item_id, 'rarity', v_rarity, 'outcome', 'new'));
    end if;
  end loop;

  if p_currency_type <> 'free' and v_is_special then
    insert into public.user_gacha_pity_points (user_id, pity_master_id, current_points)
    values (p_user_id, 'pity_special_common', p_pull_count)
    on conflict (user_id, pity_master_id) do update
      set current_points = public.user_gacha_pity_points.current_points + p_pull_count,
          updated_at = now();
    v_pity_after := v_pity_before + p_pull_count;
  else
    v_pity_after := v_pity_before;
  end if;

  perform public.record_funnel_milestone(p_user_id, 'first_gacha',
    jsonb_build_object('gachaId', p_gacha_id, 'pullCount', p_pull_count));
  select cash, neon_diamonds into v_user from public.users where id = p_user_id;
  v_response := jsonb_build_object(
    'status', 'success', 'request_id', p_request_id, 'results', v_result,
    'cash', v_user.cash, 'diamonds', v_user.neon_diamonds,
    'pity_before', v_pity_before, 'pity_after', v_pity_after);
  update public.gacha_execution_history
  set pity_after = v_pity_after, result_payload = v_response,
      status = 'COMPLETED', completed_at = now()
  where user_id = p_user_id and request_id = p_request_id;
  return v_response;
end;
$$;

create or replace function public.execute_tutorial_character_gacha(p_request_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_history record;
  v_existing record;
  v_results jsonb := '[]'::jsonb;
  v_response jsonb;
  v_item_id text;
  v_rarity text;
  v_index integer;
  v_inserted integer;
  v_progress jsonb;
begin
  if v_user_id is null then raise exception 'authentication required' using errcode='42501'; end if;
  if p_request_id is null then raise exception 'request_id is required' using errcode='22023'; end if;
  if not exists(select 1 from public.tutorial_progress where user_id=v_user_id and step_id='FREE_GACHA') then
    raise exception 'tutorial gacha is unavailable' using errcode='42501';
  end if;

  insert into public.gacha_execution_history(
    user_id,request_id,gacha_id,payment_source,pull_count,cost_amount,pity_before,pity_after
  ) values(v_user_id,p_request_id,'CHAR_NORMAL','free',10,0,0,0)
  on conflict(user_id,request_id) do nothing;
  get diagnostics v_inserted=row_count;
  if v_inserted=0 then
    select * into v_history from public.gacha_execution_history
    where user_id=v_user_id and request_id=p_request_id for update;
    if v_history.gacha_id<>'CHAR_NORMAL' or v_history.pull_count<>10 then
      raise exception 'request_id was already used for a different request';
    end if;
    if v_history.status='COMPLETED' and v_history.result_payload is not null then
      return v_history.result_payload;
    end if;
    raise exception 'tutorial gacha request is already in progress';
  end if;

  for v_index in 1..10 loop
    if v_index=10 then
      v_rarity := 'SSR';
      v_item_id := public.draw_gacha_item('CHAR_SPECIAL','SSR');
    else
      v_rarity := public.draw_gacha_rarity('CHAR_NORMAL');
      v_item_id := public.draw_gacha_item('CHAR_NORMAL',v_rarity);
    end if;
    if v_item_id is null then raise exception 'canonical tutorial gacha bucket is empty'; end if;

    select id,awakening_level into v_existing from public.user_characters
    where user_id=v_user_id and character_id=v_item_id for update;
    if found and coalesce(v_existing.awakening_level,0)<5 then
      v_progress := public.apply_character_awakening_equivalent(v_user_id, v_existing.id, 1);
      v_results:=v_results||jsonb_build_array(jsonb_build_object(
        'type','CHARACTER','character_id',v_item_id,'rarity',v_rarity,
        'outcome',v_progress->>'outcome','awakening_progress_added',1,
        'awakening_level',(v_progress->>'awakening_level')::integer,
        'awakening_progress',(v_progress->>'awakening_progress')::integer,
        'awakening_required',(v_progress->>'awakening_required')::integer,
        'tutorial_slot',v_index));
    elsif found then
      insert into public.user_items(user_id,item_id,quantity) values(v_user_id,'AWAKENING_BOOK',1)
      on conflict(user_id,item_id) do update set quantity=public.user_items.quantity+1,updated_at=now();
      v_results:=v_results||jsonb_build_array(jsonb_build_object('type','CHARACTER','character_id',v_item_id,'rarity',v_rarity,'outcome','converted','converted_item_id','AWAKENING_BOOK','converted_quantity',1,'tutorial_slot',v_index));
    else
      insert into public.user_characters(user_id,character_id,level,awakening_level) values(v_user_id,v_item_id,1,0);
      v_results:=v_results||jsonb_build_array(jsonb_build_object('type','CHARACTER','character_id',v_item_id,'rarity',v_rarity,'outcome','new','tutorial_slot',v_index));
    end if;
  end loop;

  perform public.record_funnel_milestone(v_user_id,'first_gacha',jsonb_build_object('source','tutorial_guaranteed_ssr','pullCount',10));
  v_response:=jsonb_build_object('status','success','request_id',p_request_id,'results',v_results,'tutorial',true,'guaranteed_ssr_slot',10);
  update public.gacha_execution_history set result_payload=v_response,status='COMPLETED',completed_at=now()
  where user_id=v_user_id and request_id=p_request_id;
  return v_response;
end;
$$;

CREATE OR REPLACE FUNCTION public.exchange_pity_reward(
  p_user_id uuid,
  p_reward_type text,
  p_reward_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_points integer;
  v_exists boolean;
  v_awaken integer;
  v_character_row_id uuid;
  v_progress jsonb;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  IF p_reward_type NOT IN ('CHARACTER','SKILL','EQUIPMENT') OR p_reward_id IS NULL OR p_reward_id = '' THEN
    RAISE EXCEPTION 'invalid pity reward';
  END IF;

  SELECT current_points INTO v_points
  FROM public.user_gacha_pity_points
  WHERE user_id = p_user_id AND pity_master_id = 'pity_special_common'
  FOR UPDATE;
  IF COALESCE(v_points, 0) < 200 THEN
    RAISE EXCEPTION 'insufficient pity points';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.gacha_items_master
    WHERE item_id = p_reward_id
      AND gacha_id LIKE CASE p_reward_type WHEN 'CHARACTER' THEN 'CHAR_%' WHEN 'SKILL' THEN 'SKILL_%' ELSE 'EQUIP_%' END
  ) INTO v_exists;
  IF NOT v_exists THEN RAISE EXCEPTION 'invalid pity reward'; END IF;

  UPDATE public.user_gacha_pity_points
  SET current_points = v_points - 200, updated_at = now()
  WHERE user_id = p_user_id AND pity_master_id = 'pity_special_common';

  IF p_reward_type = 'CHARACTER' THEN
    SELECT id, awakening_level INTO v_character_row_id, v_awaken FROM public.user_characters
    WHERE user_id = p_user_id AND character_id = p_reward_id ORDER BY id LIMIT 1 FOR UPDATE;
    IF v_character_row_id IS NULL THEN
      INSERT INTO public.user_characters (user_id, character_id, level, awakening_level, awakening_progress) VALUES (p_user_id, p_reward_id, 1, 0, 0);
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'new');
    ELSIF v_awaken >= 5 THEN
      INSERT INTO public.user_items (user_id, item_id, quantity) VALUES (p_user_id, 'AWAKENING_BOOK', 1)
      ON CONFLICT (user_id, item_id) DO UPDATE SET quantity = public.user_items.quantity + 1, updated_at = now();
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'converted', 'converted_item_id', 'AWAKENING_BOOK', 'converted_quantity', 1);
    ELSE
      v_progress := public.apply_character_awakening_equivalent(p_user_id, v_character_row_id, 1);
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id,
        'outcome', v_progress->>'outcome', 'awakening_progress_added', 1,
        'awakening_level', (v_progress->>'awakening_level')::integer,
        'awakening_progress', (v_progress->>'awakening_progress')::integer,
        'awakening_required', (v_progress->>'awakening_required')::integer);
    END IF;
  ELSIF p_reward_type = 'SKILL' THEN
    SELECT plus_val INTO v_awaken FROM public.user_skills WHERE user_id = p_user_id AND skill_card_id = p_reward_id ORDER BY id LIMIT 1 FOR UPDATE;
    IF v_awaken IS NULL THEN
      INSERT INTO public.user_skills (user_id, skill_card_id, plus_val) VALUES (p_user_id, p_reward_id, 0);
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'new');
    ELSIF v_awaken >= 10 THEN
      INSERT INTO public.user_items (user_id, item_id, quantity) VALUES (p_user_id, 'SKILL_MANUAL', 2)
      ON CONFLICT (user_id, item_id) DO UPDATE SET quantity = public.user_items.quantity + 2;
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'converted');
    ELSE
      UPDATE public.user_skills SET plus_val = v_awaken + 1 WHERE user_id = p_user_id AND skill_card_id = p_reward_id;
      RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'limit_break');
    END IF;
  ELSE
    INSERT INTO public.user_equipments (user_id, equipment_id, level, plus_val, random_options) VALUES (p_user_id, p_reward_id, 1, 0, '[]'::jsonb);
    RETURN jsonb_build_object('type', p_reward_type, 'item_id', p_reward_id, 'outcome', 'new');
  END IF;
END;
$$;

update public.canonical_item_master
set description='任意キャラクターへ1 copy-equivalentを加算する限定供給素材です。',
    runtime_usage='{"copyEquivalentValue":1,"manualAwakeningCost":1,"duplicateOverflowQuantity":1,"cashCost":0}'::jsonb
where version='2026-08-22' and item_id='AWAKENING_BOOK';

update public.login_bonus_master set item_id='SPECIAL_TICKET_SKILL',item_name='SPスキルチケット 1' where day_number=15;
update public.login_bonus_master set item_id='SPECIAL_TICKET_EQUIPMENT',item_name='SP装備チケット 1' where day_number=20;
update public.canonical_reward_supply_sources
set status='FROZEN',notes='30-day fixed supply: Character/Skill/Equipment Special Tickets 2/1/1 and Awakening Book 1'
where version='2026-08-22' and source='LOGIN_BONUS';

do $$ begin
  if public.canonical_character_awakening_required(0)<>1 or public.canonical_character_awakening_required(1)<>1
     or public.canonical_character_awakening_required(2)<>2 or public.canonical_character_awakening_required(3)<>3
     or public.canonical_character_awakening_required(4)<>4 or public.canonical_character_awakening_required(5)<>0 then
    raise exception 'Character awakening copy-equivalent curve mismatch';
  end if;
  if (select count(*) from public.login_bonus_master where item_id='SPECIAL_TICKET_CHARACTER')<>2
     or (select count(*) from public.login_bonus_master where item_id='SPECIAL_TICKET_SKILL')<>1
     or (select count(*) from public.login_bonus_master where item_id='SPECIAL_TICKET_EQUIPMENT')<>1 then
    raise exception 'Login Special Ticket allocation mismatch';
  end if;
end $$;

commit;
