-- Generated by scripts/generate_battle_equipment_master.mjs.
-- Open Beta M2-4a: server-authoritative equipment stats in patrol snapshots.

create table if not exists public.equipment_battle_master (
  equipment_id text primary key,
  display_name text not null,
  rarity text not null check (rarity in ('N', 'R', 'SR', 'SSR')),
  slot_type text not null check (slot_type in ('WEAPON', 'HEAD', 'BODY', 'LEGS', 'ACCESSORY')),
  hp integer not null default 0,
  atk integer not null default 0,
  def integer not null default 0,
  spd integer not null default 0,
  luk integer not null default 0,
  is_exclusive boolean not null default false,
  exclusive_character_id text
);

insert into public.equipment_battle_master (
  equipment_id, display_name, rarity, slot_type,
  hp, atk, def, spd, luk, is_exclusive, exclusive_character_id
)
values
  ('WEAPON_001', 'ストリートナイフ', 'N', 'WEAPON', 0, 5, 0, 0, 0, false, null),
  ('WEAPON_002', '9mmハンドガン', 'N', 'WEAPON', 0, 8, 0, 0, 0, false, null),
  ('WEAPON_003', '金属バット', 'N', 'WEAPON', 0, 10, 0, 0, 0, false, null),
  ('WEAPON_004', 'サバイバルマチェテ', 'N', 'WEAPON', 0, 12, 0, -1, 0, false, null),
  ('WEAPON_005', '特殊警棒', 'N', 'WEAPON', 0, 7, 3, 0, 0, false, null),
  ('WEAPON_006', '折りたたみカミソリ', 'N', 'WEAPON', 0, 6, 0, 0, 2, false, null),
  ('WEAPON_007', '鉄パイプ', 'N', 'WEAPON', 0, 9, 0, 0, 0, false, null),
  ('WEAPON_008', 'メリケンサック', 'N', 'WEAPON', 0, 6, 0, 1, 0, false, null),
  ('WEAPON_009', '錆びたバール', 'N', 'WEAPON', 0, 11, 0, -1, 0, false, null),
  ('WEAPON_010', 'バスターマグナム', 'N', 'WEAPON', 0, 13, 0, -2, 0, false, null),
  ('WEAPON_011', 'ダガー', 'R', 'WEAPON', 0, 15, 0, 0, 3, false, null),
  ('WEAPON_012', 'カスタムピストル', 'R', 'WEAPON', 0, 18, 0, 2, 0, false, null),
  ('WEAPON_013', 'ソウドオフ・ショットガン', 'R', 'WEAPON', 0, 25, 0, -3, 0, false, null),
  ('WEAPON_014', 'コンバットナイフ', 'R', 'WEAPON', 0, 16, 0, 0, 4, false, null),
  ('WEAPON_015', '電撃警棒', 'R', 'WEAPON', 0, 14, 0, 3, 0, false, null),
  ('WEAPON_016', '消音サブマシンガン', 'R', 'WEAPON', 0, 22, 0, 1, 0, false, null),
  ('WEAPON_017', 'ヘヴィスレッジハマー', 'R', 'WEAPON', 0, 35, 0, -5, 0, false, null),
  ('WEAPON_018', 'カスタムバタフライ', 'R', 'WEAPON', 0, 17, 0, 0, 5, false, null),
  ('WEAPON_019', 'ワイヤーソー', 'R', 'WEAPON', 0, 19, 0, 2, 0, false, null),
  ('WEAPON_020', '競技用コンポジットボウ', 'R', 'WEAPON', 0, 21, 0, 0, 2, false, null),
  ('WEAPON_021', 'チタンナックルクロー', 'R', 'WEAPON', 0, 18, 0, 3, 0, false, null),
  ('WEAPON_022', 'オートマチックマグナム', 'R', 'WEAPON', 0, 28, 0, -3, 0, false, null),
  ('WEAPON_023', 'スタンアサシンダガー', 'SR', 'WEAPON', 0, 30, 0, 0, 5, false, null),
  ('WEAPON_024', '消音サプレッサーSMG', 'SR', 'WEAPON', 0, 35, 0, 5, 0, false, null),
  ('WEAPON_025', 'インダストリアル・デモリッシャー', 'SR', 'WEAPON', 0, 55, 0, -5, 0, false, null),
  ('WEAPON_026', '仕込み日本刀『黒曜』', 'SR', 'WEAPON', 0, 45, 0, 0, 8, false, null),
  ('WEAPON_027', 'アサルトライフル', 'SR', 'WEAPON', 0, 48, 0, -1, 0, false, null),
  ('WEAPON_028', '超硬度カーボンブレード', 'SR', 'WEAPON', 0, 42, 0, 0, 10, false, null),
  ('WEAPON_029', '化学注入式ダガー', 'SR', 'WEAPON', 0, 34, 0, 0, 15, false, null),
  ('WEAPON_030', '散弾銃『レイザー』', 'SR', 'WEAPON', 0, 47, 0, -3, 0, false, null),
  ('WEAPON_031', 'ヘヴィリボルバー『コフィン』', 'SR', 'WEAPON', 0, 50, 0, 0, 5, false, null),
  ('WEAPON_032', 'デュアルカスタムピストル', 'SR', 'WEAPON', 0, 38, 0, 7, 0, false, null),
  ('WEAPON_033', 'スタン警棒カスタム', 'SR', 'WEAPON', 0, 32, 12, 0, 0, false, null),
  ('WEAPON_034', 'アサシンマチェテ', 'SR', 'WEAPON', 0, 41, 0, 0, 10, false, null),
  ('WEAPON_035', 'コンパクトサブピストル', 'SR', 'WEAPON', 0, 36, 0, 6, 0, false, null),
  ('WEAPON_036', 'カタナ『影打ち』', 'SR', 'WEAPON', 0, 43, 0, 0, 9, false, null),
  ('WEAPON_037', '消音スナイパーライフル', 'SR', 'WEAPON', 0, 53, 0, -4, 0, false, null),
  ('WEAPON_038', 'スチールハンドクロー', 'SR', 'WEAPON', 0, 33, 0, 9, 0, false, null),
  ('WEAPON_039', 'サイレントスチール弓', 'SR', 'WEAPON', 0, 39, 0, 0, 12, false, null),
  ('WEAPON_040', '変形蛇腹刃', 'SR', 'WEAPON', 0, 40, 0, 4, 0, false, null),
  ('WEAPON_041', 'カービンライフル', 'SR', 'WEAPON', 0, 46, 8, 0, 0, false, null),
  ('WEAPON_042', 'アイアンナックル『阿修羅』', 'SR', 'WEAPON', 0, 37, 0, 8, 0, false, null),
  ('WEAPON_043', 'デス・バイパー', 'SSR', 'WEAPON', 0, 70, 0, 8, 15, false, null),
  ('WEAPON_044', 'タクティカル・カタナ『電光石火』', 'SSR', 'WEAPON', 0, 65, 0, 20, 10, false, null),
  ('WEAPON_045', 'ショットガン『終末の鐘』', 'SSR', 'WEAPON', 150, 85, 0, -5, 0, false, null),
  ('WEAPON_046', '【保留専用：レオン専用】インゴット・ファング', 'SSR', 'WEAPON', 0, 75, 0, 6, 20, true, '99999999-9999-9999-9999-999999999999'),
  ('WEAPON_047', '【レイジ専用】レヴ・イグニッション', 'SSR', 'WEAPON', 0, 80, 0, 5, 10, true, '11111111-1111-1111-1111-111111111111'),
  ('WEAPON_048', '【ルイ専用】コマンド・キーブレード', 'SSR', 'WEAPON', 80, 60, 0, 25, 0, true, '33333333-3333-3333-3333-333333333333'),
  ('WEAPON_049', '【チャン専用】毒蛇の黒刃', 'SSR', 'WEAPON', 0, 72, 0, 10, 15, true, '22222222-2222-2222-2222-222222222222'),
  ('WEAPON_050', '【保留専用：ユウキ専用】支配者の鉄扇', 'SSR', 'WEAPON', 0, 75, 20, 0, 15, true, '99999999-9999-9999-9999-999999999999'),
  ('HEAD_001', 'ストリートキャップ', 'N', 'HEAD', 30, 0, 0, 0, 0, false, null),
  ('HEAD_002', 'パンクバンダナ', 'N', 'HEAD', 20, 0, 0, 1, 0, false, null),
  ('HEAD_003', 'ニットキャップ', 'N', 'HEAD', 25, 0, 1, 0, 0, false, null),
  ('HEAD_004', 'ワークキャップ', 'N', 'HEAD', 35, 0, 0, 0, 0, false, null),
  ('HEAD_005', 'サングラス', 'R', 'HEAD', 80, 0, 0, 0, 2, false, null),
  ('HEAD_006', 'ハッカーヘッドセット', 'R', 'HEAD', 70, 0, 0, 3, 0, false, null),
  ('HEAD_007', 'マフィアフェドラ', 'R', 'HEAD', 90, 0, 0, 0, 4, false, null),
  ('HEAD_008', '防毒マスク', 'R', 'HEAD', 100, 0, 0, 0, 0, false, null),
  ('HEAD_009', 'カーボンライダーヘルメット', 'R', 'HEAD', 120, 0, 4, 0, 0, false, null),
  ('HEAD_010', 'アンティークゴーグル', 'R', 'HEAD', 75, 0, 0, 0, 5, false, null),
  ('HEAD_011', 'バリスティックヘルメット', 'SR', 'HEAD', 200, 0, 10, 0, 0, false, null),
  ('HEAD_012', 'マルチナイトビジョンゴーグル', 'SR', 'HEAD', 180, 0, 0, 0, 8, false, null),
  ('HEAD_013', '重工業プロテクト溶接マスク', 'SR', 'HEAD', 220, 0, 0, 0, 0, false, null),
  ('HEAD_014', 'バリスティックフェイスシールド', 'SR', 'HEAD', 250, 0, 15, 0, 0, false, null),
  ('HEAD_015', 'タクティカル・スマートグラス', 'SR', 'HEAD', 150, 0, 0, 8, 0, false, null),
  ('HEAD_016', '隠密用アサシンフード', 'SR', 'HEAD', 170, 0, 0, 0, 0, false, null),
  ('HEAD_017', 'タクティカル・バイザー『千里眼』', 'SSR', 'HEAD', 380, 0, 0, 10, 10, false, null),
  ('HEAD_018', 'ヘルメット『防塁』', 'SSR', 'HEAD', 500, 0, 20, 0, 0, false, null),
  ('HEAD_019', '【保留専用：ユウキ専用】支配者のモノクル', 'SSR', 'HEAD', 400, 0, 0, 0, 15, true, '99999999-9999-9999-9999-999999999999'),
  ('HEAD_020', '【セリカ専用】艶花の黒簪', 'SSR', 'HEAD', 350, 0, 0, 12, 15, true, '99999999-9999-9999-9999-999999999999'),
  ('BODY_001', 'ウインドブレーカー', 'N', 'BODY', 50, 0, 5, 0, 0, false, null),
  ('BODY_002', 'デニムベスト', 'N', 'BODY', 60, 0, 6, 0, 0, false, null),
  ('BODY_003', '作業用つなぎ', 'N', 'BODY', 65, 0, 7, 0, 0, false, null),
  ('BODY_004', 'サテンブルゾン', 'N', 'BODY', 55, 0, 5, 0, 0, false, null),
  ('BODY_005', 'レザージャケット', 'N', 'BODY', 70, 0, 8, 0, 0, false, null),
  ('BODY_006', 'ルーズサイズフーディ', 'N', 'BODY', 80, 0, 4, 0, 0, false, null),
  ('BODY_007', 'ブランドパーカー', 'R', 'BODY', 150, 0, 15, 0, 0, false, null),
  ('BODY_008', 'ロングレザーコート', 'R', 'BODY', 180, 0, 18, 0, 0, false, null),
  ('BODY_009', 'ダブルライダース', 'R', 'BODY', 160, 0, 20, 0, 0, false, null),
  ('BODY_010', 'インナーシャツ', 'R', 'BODY', 190, 0, 14, 0, 0, false, null),
  ('BODY_011', 'ワークデニムジャケット', 'R', 'BODY', 170, 0, 16, 0, 0, false, null),
  ('BODY_012', 'プロテクトパファーベスト', 'R', 'BODY', 195, 0, 17, 0, 0, false, null),
  ('BODY_013', 'フライトジャケット', 'R', 'BODY', 175, 0, 19, 0, 0, false, null),
  ('BODY_014', '防弾ベスト', 'SR', 'BODY', 300, 0, 35, 0, 0, false, null),
  ('BODY_015', 'アサシンテックコート', 'SR', 'BODY', 280, 0, 0, 5, 0, false, null),
  ('BODY_016', '強化耐衝撃重装アーマー', 'SR', 'BODY', 450, 0, 50, -3, 0, false, null),
  ('BODY_017', '防刃ファイバーアウター', 'SR', 'BODY', 350, 0, 30, 0, 0, false, null),
  ('BODY_018', '防弾ダブルスーツジャケット', 'SR', 'BODY', 320, 0, 28, 0, 8, false, null),
  ('BODY_019', 'パンクスタッズレザーライダース', 'SR', 'BODY', 260, 0, 36, 0, 0, false, null),
  ('BODY_020', '重作業用リギングベスト', 'SR', 'BODY', 310, 8, 45, 0, 0, false, null),
  ('BODY_021', 'ウインドブレーカー・カスタム', 'SR', 'BODY', 330, 0, 31, 4, 0, false, null),
  ('BODY_022', '高級ウールチェスターコート', 'SR', 'BODY', 360, 0, 29, 0, 10, false, null),
  ('BODY_023', 'タクティカルベスト『盾壁』', 'SSR', 'BODY', 550, 0, 58, -2, 0, false, null),
  ('BODY_024', 'タクティカル・ステルスジャケット', 'SSR', 'BODY', 480, 0, 40, 10, 0, false, null),
  ('BODY_025', '【保留専用：カイト専用】ヴェルヴェット・コート', 'SSR', 'BODY', 600, 0, 60, 0, 0, true, '99999999-9999-9999-9999-999999999999'),
  ('BODY_026', '【レイジ専用】覇王のライダース', 'SSR', 'BODY', 650, 15, 55, 0, 0, true, '11111111-1111-1111-1111-111111111111'),
  ('BODY_027', '【チャン専用】蛇紋のシルクシャツ', 'SSR', 'BODY', 550, 0, 45, 0, 20, true, '22222222-2222-2222-2222-222222222222'),
  ('BODY_028', '【ルイ専用】タクティカル・ミリタリーワンピ', 'SSR', 'BODY', 580, 0, 40, 12, 0, true, '33333333-3333-3333-3333-333333333333'),
  ('BODY_029', '【ミオ専用】ボルドーホストスーツ', 'SSR', 'BODY', 570, 0, 48, 0, 18, true, '99999999-9999-9999-9999-999999999999'),
  ('BODY_030', '【ケンゴ専用】般若刺繍のスカジャン', 'SSR', 'BODY', 620, 10, 52, 0, 0, true, '99999999-9999-9999-9999-999999999999'),
  ('LEGS_001', 'テックジョガー', 'N', 'LEGS', 0, 0, 3, 2, 0, false, null),
  ('LEGS_002', 'ダメージジーンズ', 'N', 'LEGS', 0, 0, 2, 0, 1, false, null),
  ('LEGS_003', 'ヘヴィカーゴパンツ', 'N', 'LEGS', 20, 0, 4, 0, 0, false, null),
  ('LEGS_004', 'スポーツショーツ', 'N', 'LEGS', 0, 0, 1, 3, 0, false, null),
  ('LEGS_005', '加圧コンプレッションパンツ', 'R', 'LEGS', 0, 0, 10, 5, 0, false, null),
  ('LEGS_006', 'レザーライダーパンツ', 'R', 'LEGS', 50, 0, 15, 0, 0, false, null),
  ('LEGS_007', '強化カーゴパンツ', 'R', 'LEGS', 0, 0, 12, 3, 0, false, null),
  ('LEGS_008', 'サルエルスウェット', 'R', 'LEGS', 0, 0, 9, 4, 0, false, null),
  ('LEGS_009', 'ストレッチスキニー', 'R', 'LEGS', 0, 0, 8, 0, 3, false, null),
  ('LEGS_010', '作業用オーバーオール', 'R', 'LEGS', 40, 0, 14, 0, 0, false, null),
  ('LEGS_011', 'プロテクト・コンバットパンツ', 'SR', 'LEGS', 100, 0, 25, 3, 0, false, null),
  ('LEGS_012', '強化スチールトゥーブーツ', 'SR', 'LEGS', 0, 0, 22, 8, 0, false, null),
  ('LEGS_013', 'ナノカーボン・ランニングスパッツ', 'SR', 'LEGS', 0, 0, 18, 12, 0, false, null),
  ('LEGS_014', 'ヘヴィタクティカルグリーブ', 'SR', 'LEGS', 150, 0, 35, -2, 0, false, null),
  ('LEGS_015', '高通気テックメッシュパンツ', 'SR', 'LEGS', 0, 0, 20, 10, 0, false, null),
  ('LEGS_016', 'スパイクスタッズレザーパンツ', 'SR', 'LEGS', 0, 0, 24, 0, 6, false, null),
  ('LEGS_017', 'カーボンファイバー・スニーカー『閃光』', 'SSR', 'LEGS', 0, 0, 20, 20, 0, false, null),
  ('LEGS_018', 'アーマードブーツ『防塁』', 'SSR', 'LEGS', 180, 0, 38, -2, 0, false, null),
  ('LEGS_019', '【保留専用：コハル専用】スピードスター・スニーカー', 'SSR', 'LEGS', 0, 0, 20, 15, 0, true, '99999999-9999-9999-9999-999999999999'),
  ('LEGS_020', '【保留専用：サクラ専用】漆黒のアサシンロングブーツ', 'SSR', 'LEGS', 0, 0, 22, 10, 10, true, '99999999-9999-9999-9999-999999999999'),
  ('LEGS_021', 'シャドウランナー', 'SSR', 'LEGS', 200, 0, 8, 15, 0, false, null),
  ('ACCESSORY_001', 'ネオンスタッドピアス', 'N', 'ACCESSORY', 0, 0, 0, 0, 1, false, null),
  ('ACCESSORY_002', 'スチールフラットリング', 'N', 'ACCESSORY', 0, 0, 0, 0, 2, false, null),
  ('ACCESSORY_003', 'レザーベルトチョーカー', 'N', 'ACCESSORY', 10, 0, 0, 0, 0, false, null),
  ('ACCESSORY_004', '刻印付きドッグタグ', 'N', 'ACCESSORY', 0, 2, 0, 0, 0, false, null),
  ('ACCESSORY_005', 'ラバーリストバンド', 'N', 'ACCESSORY', 0, 0, 0, 1, 0, false, null),
  ('ACCESSORY_006', 'シルバーチェーンネックレス', 'N', 'ACCESSORY', 0, 0, 0, 0, 3, false, null),
  ('ACCESSORY_007', '真鍮アームバングル', 'N', 'ACCESSORY', 0, 0, 2, 0, 0, false, null),
  ('ACCESSORY_008', 'ネオンラバーキーホルダー', 'N', 'ACCESSORY', 0, 0, 0, 0, 2, false, null),
  ('ACCESSORY_009', 'スカルピンバッジ', 'N', 'ACCESSORY', 15, 0, 0, 0, 0, false, null),
  ('ACCESSORY_010', '編み込み革ブレス', 'N', 'ACCESSORY', 0, 0, 1, 0, 1, false, null),
  ('ACCESSORY_011', 'ブランドクロノグラフ', 'R', 'ACCESSORY', 50, 0, 0, 2, 0, false, null),
  ('ACCESSORY_012', '極太ゴールドチェーン', 'R', 'ACCESSORY', 0, 0, 0, 0, 6, false, null),
  ('ACCESSORY_013', 'スクエア印台リング', 'R', 'ACCESSORY', 0, 5, 0, 0, 4, false, null),
  ('ACCESSORY_014', 'チタンチョーカー', 'R', 'ACCESSORY', 0, 0, 8, 2, 0, false, null),
  ('ACCESSORY_015', 'スパイクスタッズリストバンド', 'R', 'ACCESSORY', 0, 4, 4, 0, 0, false, null),
  ('ACCESSORY_016', 'カミソリ刃ペンダント', 'R', 'ACCESSORY', 0, 6, 0, 0, 0, false, null),
  ('ACCESSORY_017', 'ギャンブラーダイス', 'R', 'ACCESSORY', 0, 0, 0, 0, 8, false, null),
  ('ACCESSORY_018', 'ユーティリティベルト', 'R', 'ACCESSORY', 30, 0, 10, 0, 0, false, null),
  ('ACCESSORY_019', 'シルバーゴシックスカルリング', 'R', 'ACCESSORY', 0, 4, 0, 0, 5, false, null),
  ('ACCESSORY_020', 'スタッドイヤーカフ', 'R', 'ACCESSORY', 0, 0, 0, 3, 0, false, null),
  ('ACCESSORY_021', 'スチールウォレットチェーン', 'R', 'ACCESSORY', 0, 0, 0, 0, 7, false, null),
  ('ACCESSORY_022', 'ゴシッククロスペンダント', 'R', 'ACCESSORY', 60, 0, 4, 0, 0, false, null),
  ('ACCESSORY_023', 'スマートフィットトラッカー', 'R', 'ACCESSORY', 40, 0, 0, 4, 0, false, null),
  ('ACCESSORY_024', 'コブラバングル', 'R', 'ACCESSORY', 0, 5, 0, 0, 5, false, null),
  ('ACCESSORY_025', '弾丸シェルネックレス', 'R', 'ACCESSORY', 0, 8, 0, 0, 0, false, null),
  ('ACCESSORY_026', 'アンティークロケットペンダント', 'SR', 'ACCESSORY', 100, 0, 0, 0, 5, false, null),
  ('ACCESSORY_027', 'プラチナ印台リング', 'SR', 'ACCESSORY', 0, 10, 0, 0, 10, false, null),
  ('ACCESSORY_028', '解錠ツールキーホルダー', 'SR', 'ACCESSORY', 0, 0, 8, 6, 0, false, null),
  ('ACCESSORY_029', 'ブルーサファイアリング', 'SR', 'ACCESSORY', 0, 0, 0, 4, 12, false, null),
  ('ACCESSORY_030', '極太クロームチェーン', 'SR', 'ACCESSORY', 0, 12, 0, 0, 8, false, null),
  ('ACCESSORY_031', '死神のシルバーチャーム', 'SR', 'ACCESSORY', 200, 0, 0, 0, 0, false, null),
  ('ACCESSORY_032', '百合の刻印ネックレス', 'SR', 'ACCESSORY', 0, 14, 0, 0, 0, false, null),
  ('ACCESSORY_033', 'ヘヴィスパイクチョーカー', 'SR', 'ACCESSORY', 0, 8, 12, 0, 0, false, null),
  ('ACCESSORY_034', 'ダイヤモンドアンカーリング', 'SR', 'ACCESSORY', 80, 0, 0, 0, 15, false, null),
  ('ACCESSORY_035', '原石ターコイズバングル', 'SR', 'ACCESSORY', 0, 0, 15, 0, 9, false, null),
  ('ACCESSORY_036', '天然水晶チャーム', 'SR', 'ACCESSORY', 180, 0, 0, 0, 10, false, null),
  ('ACCESSORY_037', 'スマートウォッチPRO', 'SR', 'ACCESSORY', 120, 0, 0, 10, 0, false, null),
  ('ACCESSORY_038', '黒のトライバルシール', 'SR', 'ACCESSORY', 0, 15, -5, 0, 0, false, null),
  ('ACCESSORY_039', '鉄製シャックルブレス', 'SR', 'ACCESSORY', 0, 0, 12, 0, 10, false, null),
  ('ACCESSORY_040', 'ルビーゴールドチャーム', 'SR', 'ACCESSORY', 0, 16, 0, 0, 0, false, null),
  ('ACCESSORY_041', '強化カーボン戦闘グローブ', 'SR', 'ACCESSORY', 0, 10, 10, 2, 0, false, null),
  ('ACCESSORY_042', 'スネークアンクレット', 'SR', 'ACCESSORY', 0, 0, 0, 8, 11, false, null),
  ('ACCESSORY_043', 'スチールスカルキーチェーン', 'SR', 'ACCESSORY', 0, 0, 0, 0, 14, false, null),
  ('ACCESSORY_044', 'チタンアスリートバンド', 'SR', 'ACCESSORY', 100, 0, 18, 0, 0, false, null),
  ('ACCESSORY_045', 'オパール襟ピンバッジ', 'SR', 'ACCESSORY', 0, 0, 0, 0, 18, false, null),
  ('ACCESSORY_046', '極道幹部の翡翠守り', 'SSR', 'ACCESSORY', 50, 5, 5, 5, 5, false, null),
  ('ACCESSORY_047', '【保留専用：サクラ専用】漆塗りの桜根付', 'SSR', 'ACCESSORY', 0, 0, 0, 10, 10, true, '99999999-9999-9999-9999-999999999999'),
  ('ACCESSORY_048', '【レイジ専用】蜘蛛の巣の首飾り', 'SSR', 'ACCESSORY', 0, 20, 0, 8, 0, true, '11111111-1111-1111-1111-111111111111'),
  ('ACCESSORY_049', '【ルイ専用】タクティカル・イヤーカフ', 'SSR', 'ACCESSORY', 0, 0, 15, 15, 0, true, '33333333-3333-3333-3333-333333333333'),
  ('ACCESSORY_050', '【ケンゴ専用】狂犬の数珠', 'SSR', 'ACCESSORY', 150, 25, 0, 0, 0, true, '99999999-9999-9999-9999-999999999999'),
  ('ACCESSORY_051', '福呼びの守り', 'SSR', 'ACCESSORY', 100, 0, 0, 0, 25, false, null)
on conflict (equipment_id) do update set
  display_name = excluded.display_name,
  rarity = excluded.rarity,
  slot_type = excluded.slot_type,
  hp = excluded.hp,
  atk = excluded.atk,
  def = excluded.def,
  spd = excluded.spd,
  luk = excluded.luk,
  is_exclusive = excluded.is_exclusive,
  exclusive_character_id = excluded.exclusive_character_id;

create or replace function public.create_patrol_battle_replay(
  p_patrol_id uuid,
  p_tactic_id text default 'ATTACK_PRIORITY'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_patrol record;
  v_deck record;
  v_player_snapshot jsonb;
  v_enemy_snapshot jsonb;
  v_replay_id uuid;
  v_server_seed bigint;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_tactic_id not in ('ATTACK_PRIORITY', 'HEAL_PRIORITY', 'SKILL_PRIORITY', 'BALANCED', 'WEAKNESS_FOCUS') then
    raise exception 'invalid tactic' using errcode = '22023';
  end if;

  select patrol.*, npc.id as npc_id, npc.npc_name, npc.enemy_data
  into v_patrol
  from public.user_patrols patrol
  join public.patrol_npcs npc on npc.quest_id = coalesce(patrol.course_id, patrol.quest_id)
  where patrol.id = p_patrol_id
    and patrol.user_id = v_user_id
    and (
      patrol.status = 'CLAIMABLE'
      or (patrol.status = 'ONGOING' and patrol.expires_at <= now())
    )
    and patrol.has_battle_event = true
    and coalesce(patrol.battle_resolved, false) = false
  order by npc.id
  limit 1
  for update of patrol;

  if not found then
    raise exception 'eligible patrol encounter not found' using errcode = 'P0002';
  end if;

  update public.user_patrols
  set status = 'CLAIMABLE'
  where id = p_patrol_id and status = 'ONGOING';

  select deck.* into v_deck
  from public.pvp_defense_decks deck
  where deck.user_id = v_user_id;

  with deck_requested(character_id, ordinality) as (
    select value, ordinality
    from unnest(array[
      v_deck.character_1_id, v_deck.character_2_id, v_deck.character_3_id,
      v_deck.character_4_id, v_deck.character_5_id
    ]) with ordinality as picked(value, ordinality)
    where value is not null
  ), requested(character_id, ordinality) as (
    select character_id, ordinality from deck_requested
    union all
    select owned.id::text, 1
    from public.user_characters owned
    where owned.user_id = v_user_id
      and owned.character_id = v_patrol.character_id
      and not exists (select 1 from deck_requested)
      and owned.id = (
        select fallback.id from public.user_characters fallback
        where fallback.user_id = v_user_id
          and fallback.character_id = v_patrol.character_id
        order by fallback.created_at
        limit 1
      )
  ), canonical_base as (
    select owned.id, owned.character_id, owned.level, owned.awakening_level,
           requested.ordinality, master.display_name, master.alignment,
           floor((growth.base_hp + (owned.level - 1) * growth.hp_gain + coalesce(awake.hp_bonus, 0)) * master.rarity_multiplier)::integer as hp,
           floor((growth.base_atk + (owned.level - 1) * growth.atk_gain + coalesce(awake.atk_bonus, 0)) * master.rarity_multiplier)::integer as atk,
           floor((growth.base_def + (owned.level - 1) * growth.def_gain + coalesce(awake.def_bonus, 0)) * master.rarity_multiplier)::integer as def,
           floor((growth.base_spd + floor((owned.level - 1) * growth.spd_gain) + coalesce(awake.spd_bonus, 0)) * master.rarity_multiplier)::integer as spd,
           floor((growth.base_luk + floor((owned.level - 1) * growth.luk_gain) + coalesce(awake.luk_bonus, 0)) * master.rarity_multiplier)::integer as luk
    from requested
    join public.user_characters owned
      on owned.user_id = v_user_id and owned.id::text = requested.character_id
    join public.character_battle_master master on master.character_id = owned.character_id
    join public.character_growth_patterns growth on growth.pattern_id = master.growth_pattern_id
    left join public.character_awakening_master awake on awake.awakening_level = owned.awakening_level
  ), canonical as (
    select base.*,
      coalesce(equipment.hp, 0)::integer as equipment_hp,
      coalesce(equipment.atk, 0)::integer as equipment_atk,
      coalesce(equipment.def, 0)::integer as equipment_def,
      coalesce(equipment.spd, 0)::integer as equipment_spd,
      coalesce(equipment.luk, 0)::integer as equipment_luk,
      coalesce(equipment.loadout, '[]'::jsonb) as equipment_loadout,
      coalesce(skills.loadout, '[]'::jsonb) as equipped_skill_refs
    from canonical_base base
    left join lateral (
      select
        sum(floor(master.hp * (1 + (greatest(coalesce(owned.level, 1), 1) - 1) * 0.05 + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as hp,
        sum(floor(master.atk * (1 + (greatest(coalesce(owned.level, 1), 1) - 1) * 0.05 + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as atk,
        sum(floor(master.def * (1 + (greatest(coalesce(owned.level, 1), 1) - 1) * 0.05 + greatest(coalesce(owned.plus_val, 0), 0) * 0.10))) as def,
        sum(master.spd) as spd,
        sum(master.luk) as luk,
        jsonb_agg(jsonb_build_object(
          'instanceId', owned.id,
          'equipmentId', master.equipment_id,
          'slotIndex', owned.slot_index,
          'level', greatest(coalesce(owned.level, 1), 1),
          'plusValue', greatest(coalesce(owned.plus_val, 0), 0)
        ) order by owned.slot_index, owned.id) as loadout
      from public.user_equipments owned
      join public.equipment_battle_master master
        on master.equipment_id = coalesce(nullif(owned.equipment_id, ''), owned.equipment_master_id)
      where owned.user_id = v_user_id
        and owned.equipped_character_id = base.id::text
        and (not master.is_exclusive or master.exclusive_character_id = base.character_id)
    ) equipment on true
    left join lateral (
      select jsonb_agg(jsonb_build_object(
        'skillId', owned.skill_card_id,
        'slotIndex', owned.slot_index,
        'plusValue', greatest(least(coalesce(owned.plus_val, 0), 10), 0),
        'effectScale', case
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 3
            then 1 + greatest(least(coalesce(owned.plus_val, 0), 10), 0) * 0.05
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 6
            then 1.15 + (greatest(least(coalesce(owned.plus_val, 0), 10), 0) - 3) * 0.04
          when greatest(least(coalesce(owned.plus_val, 0), 10), 0) <= 9
            then 1.27 + (greatest(least(coalesce(owned.plus_val, 0), 10), 0) - 6) * 0.03
          else 1.41
        end
      ) order by owned.slot_index, owned.skill_card_id) as loadout
      from public.user_skills owned
      where owned.user_id = v_user_id
        and owned.equipped_character_id = base.id::text
    ) skills on true
  )
  select jsonb_agg(jsonb_build_object(
    'id', 'ally_' || canonical.character_id,
    'name', canonical.display_name,
    'team', 'PLAYER',
    'alignment', canonical.alignment,
    'stats', jsonb_build_object(
      'hp', greatest(canonical.hp + canonical.equipment_hp, 1),
      'atk', greatest(canonical.atk + canonical.equipment_atk, 0),
      'def', greatest(canonical.def + canonical.equipment_def, 0),
      'spd', greatest(canonical.spd + canonical.equipment_spd, 0),
      'luk', greatest(canonical.luk + canonical.equipment_luk, 0)
    ),
    'equipment', canonical.equipment_loadout,
    -- Individual target/cooldown fields do not yet exist in the approved
    -- skill master. Preserve the owned loadout for audit/replay migration,
    -- but do not invent executable effects; basic attack remains canonical.
    'equippedSkillRefs', canonical.equipped_skill_refs,
    'skills', jsonb_build_array(jsonb_build_object(
      'id', 'basic_attack_' || canonical.id::text, 'name', 'Attack',
      'kind', 'ATTACK', 'target', 'ENEMY_SINGLE', 'powerPercent', 100, 'cooldown', 0
    ))
  ) order by canonical.ordinality)
  into v_player_snapshot
  from canonical;

  if coalesce(jsonb_array_length(v_player_snapshot), 0) = 0 then
    raise exception 'battle formation has no supported owned character' using errcode = '23514';
  end if;

  v_enemy_snapshot := jsonb_build_array(jsonb_build_object(
    'id', 'enemy_' || v_patrol.npc_id,
    'name', v_patrol.npc_name,
    'team', 'ENEMY',
    'alignment', 'CHAOS',
    'stats', jsonb_build_object(
      'hp', greatest(coalesce((v_patrol.enemy_data ->> 'hp')::integer, 1), 1),
      'atk', greatest(coalesce((v_patrol.enemy_data ->> 'atk')::integer, 1), 0),
      'def', greatest(coalesce((v_patrol.enemy_data ->> 'def')::integer, 0), 0),
      'spd', greatest(coalesce((v_patrol.enemy_data ->> 'spd')::integer, 1), 0),
      'luk', greatest(coalesce((v_patrol.enemy_data ->> 'luk')::integer, 0), 0)
    ),
    'skills', jsonb_build_array(jsonb_build_object(
      'id', 'npc_basic_attack', 'name', 'Attack', 'kind', 'ATTACK',
      'target', 'ENEMY_SINGLE', 'powerPercent', 100, 'cooldown', 0
    ))
  ));

  v_server_seed := floor(random() * 2147483646)::bigint + 1;
  insert into public.battle_replay_sessions (
    requester_user_id, battle_mode, source_reference_id, tactic_id,
    random_seed, player_snapshot, enemy_snapshot, resolution_authority
  ) values (
    v_user_id, 'QUEST', p_patrol_id, p_tactic_id,
    v_server_seed, v_player_snapshot, v_enemy_snapshot, 'PATROL_SERVER'
  ) returning id into v_replay_id;

  return jsonb_build_object(
    'replay_session_id', v_replay_id,
    'player_snapshot', v_player_snapshot,
    'enemy_snapshot', v_enemy_snapshot
  );
end;
$$;

revoke all on table public.equipment_battle_master from public, anon, authenticated;
revoke all on function public.create_patrol_battle_replay(uuid, text) from public, anon;
grant execute on function public.create_patrol_battle_replay(uuid, text) to authenticated;

notify pgrst, 'reload schema';
